### ISSUE TITLE
Cannot install on non-debian systems

### ISSUE THREAD

**Issue by kalinchernev** [docker/desktop-linux#10]
I am a Manjaro Gnome Linux user. I spent an hour trying to figure out a way to install desktop-linux on my computer, but failed.

I went through all repositories within docker organization and I did not find the sources with which I can build the app. I also tried deb-tap, and all goes ok until the dependency issue

```
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'bash-completion>=6.0.0' required by docker-desktop
```

I will try to find a way to install this dependency, but in overall I think there must be a better way to provide the app for different distributions.

**Comment by aiordache** [comment]
Hi @kalinchernev!

Here is a [package](https://desktop-stage.docker.com/linux/main/amd64/78430/docker-desktop-4.8.0-x86_64.pkg.tar.zst) for Arch-based distros.

Do you mind giving it a try please? It is an early version, it does not contain the docker cli binary, you'll have to install that separately.

**Comment by kalinchernev** [comment]
Thanks @aiordache!

Managed to download and install things. I did not manage to make actual use of the app as it won't discover containers and images, but I had to try.

Just as a brief feedback, the app uses 8GB RAM while running and not even doing anything with containers or images.

Closing the issue, thanks for your help!
