### ISSUE TITLE
Deployment is invalid: spec.template.spec.containers[0].image: Required value

### ISSUE THREAD

**Issue by mohamedGamalAbuGalala** [docker/desktop-linux#100]
- [x] I have tried the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

I tried running the same repo on mac and windows, both are working fine. and I found an issue posted here https://github.com/GoogleContainerTools/skaffold/issues/7856 complaining about the same problem, and it it's working via minikube. I don't want to switch (I tried but had much more issues with minikube)

### Expected behavior
working with no problems 
### Actual behavior
` - The Deployment "auth-depl" is invalid: spec.template.spec.containers[0].image: Required value`
### Information

  - Linux distro: Ubuntu 22.04.1 LTS
  - Docker Desktop Version: Docker Desktop 4.15.0 (93002)

### Steps to reproduce the behavior

  1. Clone https://github.com/mohamedGamalAbuGalala/learn-micro-service-ticketing
  2. install skaffold (For Linux x86_64 (amd64))
  3. run `skaffold dev`

**Comment by aiordache** [comment]
Hi @mohamedGamalAbuGalala. 
Skaffold seems to do the build and image tagging using the default Docker Engine socket. But on Linux, that is reserved for a local Docker Engine. Docker Desktop is creating the socket for its engine at `~/.docker/desktop/docker.sock`. You can get the endpoint from your current docker context (marked by *).

```
$ docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT      
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock     
desktop-linux *     moby                                                          unix:///home/user/.docker/desktop/docker.sock                                                       
```
Docker Desktop can run alongside Docker Engine and the docker context is the mechanism allowing the Docker CLI to switch between them.

If you set the env var DOCKER_HOST to point to the Docker Desktop endpoint, your deployment should work as skaffold will use Docker Desktop to build and not a local Docker engine.

Try to run  the command below after replacing the user with yours. 
```
$ DOCKER_HOST=unix:///home/<user>/.docker/desktop/docker.sock skaffold dev
```

There is nothing we can do in Docker Desktop about this. You can raise an issue in skaffold's repo for skaffold to get the socket from the current docker context and not always default to `/var/run/docker.sock`.

**Comment by torressam333** [comment]
@aiordache this solved me being able to use the built in kubernetes with docker desktop on Ubunut 22.04!
