### ISSUE TITLE
Docker freezes in "Engine stopping" forever

### ISSUE THREAD

**Issue by endersonmaia** [docker/desktop-linux#101]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: a3efaf6e-6ccd-42cf-8d36-3b755a0f7758/20221207210239

### Expected behavior

It shouldn't freeze on "Engine stopping¨, actually it shouldn't try to stop at all, since I didn't asked for it. :)

### Actual behavior

I'm using the Kubernetes provided by Docker for Desktop, to deploy some stuff (postgres, ipfs, graph-node).

When I start processing a subgraph (graph-node), after some time I can't get the logs form the Pod anymore, and Docker freezes with "Engine stopping" message, forever.

It won't stop or restart, I need to kill it by hand.

### Information

  - Linux distro: Ubuntu
  - Distro version: 22.04.1 LTS
  - Docker Desktop Version: v4.15.0

### Steps to reproduce the behavior

  1. Deploy graph-node using kubernetes
  2. dpeloy a subgrpah to this graph-node

I don't have the resources to provide the steps right now, but if you can't find any information on the Diagnostic I've uploaded, I may try to create some generic code and see if it freezes.

**Comment by aiordache** [comment]
Hi @endersonmaia. Sorry for this. Issue seems to be caused by vpnkit, the component handling the vm traffic. 
Can you try to turn it off by setting the `useVpnkit` property in `~/.docker/desktop/settings.json` to false, then quit Docker Desktop and start it again.

**Comment by endersonmaia** [comment]
@aiordache it's working after `useVpnkit: false`, thanks!

Should I keep this issue open ? 

Is that a known problem documented somewhere, or in any other related issue ?

**Comment by aiordache** [comment]
No need to keep this open. We know vpnkit is causing some problems on  Linux. We plan to disable it by default in the next release.
