### ISSUE TITLE
Linux Debian install of Docker Desktop returns several unmet dependencies

### ISSUE THREAD

**Issue by bxflourish** [docker/desktop-linux#106]
I'm totally new to all of this but doing my best and learning along the way -
I'm attempting to install Docker Desktop on my Rasberry Pi 4B 8GB running Linux Debian 11 (Bullseye) with a 64bit OS.
As far as I'm aware, I've done the work to meet the system requirements and set up the repository as instructed.

### Expected behavior
When I run the install script for docker-desktop, it should successfully run the script (minus the expected error code).

### Actual behavior
When I run the script it says I have unmet dependencies:
docker-ce-cli:amd64
libseccomp2:amd64
libcap-ng0:amd64
pass:amd64
libgtk-3-0:amd64
libx11-xcb1:amd64

I ran installs on each and they all returned as already installed (except pass which I ran) - When I ran the install script for docker-desktop again it still returned the unmet dependencies. (My guess is that it's expecting an amd processor?)

  - Linux distro: Debian
  - Distro version: 11 Bullseye
  - Docker Desktop Version: 4.15.0

### Steps to reproduce the behavior
1) Complete a fresh boot of **Raspbian OS 64bit 5.15 Debain 11 Bullseye** and set up
2) Install KVM/QEMU per https://linuxhint.com/enable_kvm_kernel_module_on_raspberry_pi_os/
3) Ensure file sharing is available by running `cat /etc/subuid` and `cat /etc/subgid` which returned the expected response
4) Set up the repository per https://docs.docker.com/engine/install/debian/#set-up-the-repository
5) Install the docker engine per https://docs.docker.com/engine/install/debian/#set-up-the-repository (unnecessary step? My first thought was that this wasn't needed so I uninstalled before running the docker-desktop install but attributed the unmet dependencies to the lack of these installs so tried again with them but still had the unmet dependencies)
6) Download and install the DEB package through `cd Downloads` per https://docs.docker.com/desktop/install/debian/

**Comment by aiordache** [comment]
Hi @bxflourish. Yes, you are trying to install a package built for amd64(x86_64) processors but RaspberryPis have ARM processors.
[Here](https://desktop-stage.docker.com/linux/main/arm64/94073/docker-desktop-4.16.0-arm64.deb) is an ARM package that you could give it a try but we cannot guarantee it will work on RPi, we do not provide support for DDL on ARM machines at the moment.
 Any feedback is much appreciated if you get it running.

**Comment by bxflourish** [comment]
@aiordache Thanks! Installing went smooth, and so far I've had no issues with using it.

**Comment by Cerexus** [comment]
@aiordache 

Do you know where i can find the latest ARM package?

**Comment by aiordache** [comment]
@Cerexus, if you replace `amd` with `arm` everywhere in the download link for the deb package, you should be able to get the arm build for that version.
`https://desktop.docker.com/linux/main/amd64/docker-desktop-4.16.2-amd64.deb `--> `https://desktop.docker.com/linux/main/arm64/docker-desktop-4.16.2-arm64.deb`
