### ISSUE TITLE
Possible bug in linux beta 4.8.0-77103

### ISSUE THREAD

**Issue by philclifford** [docker/desktop-linux#11]
- [x] I have tried with the latest version of Docker Desktop
  - n/a  - none enabled : I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 731b32a8-b852-4e1d-9616-06d3235aba06/20220430224345

### Expected behavior
Documentation states post-install script adds entry to /etc/hosts

### Actual behavior
post-install a single line comment had been added to /etc/hosts with "\n" where line terminations should be
```
$ grep kubernetes /etc/hosts
# Added by Docker Desktop\n# To allow the same kube context to work on the host and the container:\n127.0.0.1	kubernetes.docker.internal\n# End of section
```

### Information

  - Linux distro: Ubyuntu Mate
  - Distro version: 21.10
  - Docker Desktop Version:  - 
```
$ docker-desktop --version
[2022-04-30T21:39:14.975330043Z][docker-desktop][I] running under systemd
```

### Steps to reproduce the behavior
fresh first install of docker-desktop, examine hosts file

**Comment by aiordache** [comment]
Hi @philclifford! Thanks for raising the issue. 
We have added a fix for it in [this](https://desktop-stage.docker.com/linux/main/amd64/78572/docker-desktop-4.8.0-amd64.deb) build. 
If you want to test it and confirm if it works for you, that would be great. 

The new build has a few changes related to the install paths. Before trying it, the beta build must be removed and that line from `/etc/hosts` too.
The new install path for docker-desktop files should be `/opt/docker-desktop`.

**Comment by philclifford** [comment]
Thanks: testing it now.  First I removed the beta build (with `sudo apt remove ...` ) and noticed a possibly noteworthy error message, plus a typo in the output:
```
Removing docker-desktop (4.8.0-77103) ...
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Stopoing docker-desktop for logged in users
```
 ^- 's/Stopoing/Stopping' .  Otherwise looks good so I'll edit /etc/hosts and try the build

**Comment by philclifford** [comment]
Can confirm the new build installed and works well, with host file correctly changed.  I'll leave this open so you can close when you've noted the above comment or follow up it you wish. Cheers.

**Comment by aiordache** [comment]
Thank you @philclifford!
