### ISSUE TITLE
Docker Desktop stuck at "Docker Desktop Starting"

### ISSUE THREAD

**Issue by tunadag** [docker/desktop-linux#110]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 9c8da40b-af13-4860-836f-57db3a8b919d/20230109125601

### Expected behavior
 To start Docker Desktop.
### Actual behavior
 "Docker Desktop starting" forever.
### Information

  - Linux distro: Mint
  - Distro version: 21
  - Docker Desktop Version: v4.15.0

### Steps to reproduce the behavior
1-
$ service docker status 
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-01-09 14:45:10 +03; 1h 33min ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 1307 (dockerd)
      Tasks: 11
     Memory: 14.8M
        CPU: 4.979s
     CGroup: /system.slice/docker.service
             └─1307 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

2- Start Docker Desktop
3- It will be there broken forever.

**Comment by aiordache** [comment]
Hi @tunadag. The logs show some issues with vpnkit, the component handling the vm traffic. Can you set the `useVpnkit` property in `~/.docker/desktop/settings.json` to false, then quit Docker Desktop and start it again?
