### ISSUE TITLE
"Docker desktop starting..." problem - have run self diagnostics unsuccesfully.

### ISSUE THREAD

**Issue by foxmcc** [docker/desktop-linux#111]
Diagnostics ID: c8cc436e-3bed-465f-aa10-d7c9f1d7e181/20230118121540

Self diagnostics fail to work. New Linux/Docker user so unsure what to do. 

Thanks.

**Comment by aiordache** [comment]
@foxmcc You are missing the subuid/subgid config files for filesharing setup. Please check [this doc page](https://docs.docker.com/desktop/faqs/linuxfaqs/#how-do-i-enable-file-sharing) with details on how to set them.
