### ISSUE TITLE
Docker Desktop fails to start after install:  "Docker Desktop stopped..." message  displayed

### ISSUE THREAD

**Issue by bawolk** [docker/desktop-linux#113]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: ea2d748f-dd9d-4049-94b1-b537a056b96d/20230125155248

### Expected behavior
Docker Deskstop starts when application is selected
### Actual behavior
Docker Desktop displays "Docker Desktop stopped..."
### Information

The problem occurred after the initial install.  I followed the installation instructions on the Docker website.  The usual docker components are all installed.  

$ docker compose version
Docker Compose version v2.15.1

$ docker --version
Docker version 20.10.23, build 7155243

$ docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.29
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:45:08 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:42:57 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ lsb_release -idrc  # distro, version, codename, long release name
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

  - Docker Desktop Version: 4.16.2 (95914)

### Steps to reproduce the behavior

  1. Launch Docker Desktop
  2. It fails to start, displaying the "Docker Desktop stopped..." message

**Comment by aiordache** [comment]
Hi @bawolk. You need to enable virtualization for Docker Desktop  to run. 
```
Could not access KVM kernel module: No such file or directory
[2023-01-25T14:33:57.880655618Z] qemu-system-x86_64: -accel kvm: failed to initialize kvm: No such file or directory
```
You may need to enable it in the BIOS settings first.
Check [the docs](https://docs.docker.com/desktop/install/linux-install/#kvm-virtualization-support) on how to enable kvm.

**Comment by bawolk** [comment]
Thank you!  I thought I had enabled it, but when I checked, it was disabled.  Problem solving.  Sorry for taking up the bandwidth.
