### ISSUE TITLE
"Docker Desktop stopped..." vm has not started

### ISSUE THREAD

**Issue by artemave** [docker/desktop-linux#114]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7c1ff673-e3b7-490d-bb42-9cf6464710df/20230127140634

### Expected behavior

Docker desktop works.

### Actual behavior

Docker desktop is stuck with "Docker Desktop stopped..." message.

### Information

  - Linux distro: Fedora
  - Distro version: 37
  - Docker Desktop Version: 4.16.2

It's interesting that I was able to use docker desktop after the initial install. It was all fine, but I think I had to kill it at some point later as I noticed it was hoovering up 100% cpu... From then on it stopped working. Reinstalling didn't help. Reading through the diagnostic, "vm has not started" seemed relevant, hence it's in the title.

**Comment by MaxxRK** [comment]
- [ x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:5bc31f31-9c26-440d-a356-4135eda5adc6/20230202034607

I have the same issue as above.

  - Linux distro: Fedora
  - Distro version: 37
  - Docker Desktop Version: 4.16.2

### Steps to reproduce the behavior
1. Install docker engine
2. Install docker desktop
3. First run I got "Docker Desktop Stopped

This is a fresh install and I tried installing Docker Desktop as I have before on this distro just fine. Docker engine seems to run fine, but Desktop just says stopped.

I can pull images just fine, but Docker Desktop shows nothing. It looks like Docker Desktop cannot find the engine or some permissions are wrong. I do not know how I would have done that though.
```
* querying com.docker.backend process: is it running as a different user?: readlink /proc/9313/exe: permission denied
* querying com.docker.backend process: is it running as a different user?: readlink /proc/9339/exe: permission denied
* com.docker.driver.amd64-linux is not running
* qemu-system-x86_64 is not running
```

**Comment by dhanyn10** [comment]
@artemave @MaxxRK have you tried this https://github.com/docker/for-mac/issues/6527#issuecomment-1286248340 ?

**Comment by artemave** [comment]
@dhanyn10 That comment is osx specific, but I tried to uninstall and remove everything docker related (I could think of) from my machine, upgrade all the things and reinstall docker desktop, but to no avail.

**Comment by Roshan12here** [comment]
I ran into the same Problem and I fixed it by enabling VT in my pc Here is How you can do it
Enable Virtualization in BIOS:
   Restart your computer and enter BIOS settings (usually by pressing a key like F2, F12, Delete, or Esc during startup, depending on your hardware).
    Look for an option related to virtualization technology. It might be named something like "Intel VT-x" or "AMD-V". Ensure it is enabled.
    Save the BIOS settings and restart your computer.
