### ISSUE TITLE
There does not appear to be a Docker Menu

### ISSUE THREAD

**Issue by pjgoodall** [docker/desktop-linux#120]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: c57683ae-aea6-463e-a248-9225e3ff961c/20230207004439

### Expected behavior
Docker Menu as described in https://docs.docker.com/desktop/use-desktop/#the-docker-menu 
### Actual behavior
Docker Menu does not appear to exist. I wanted to return to the *Quick Start Guide* Which is supposed to be on the 'task bar'. If I click on the docker whale - which I can only assume is the task-bar, I get no response. If I hover, I get a *Running* balloon 
![Screenshot from 2023-02-07 11-40-02](https://user-images.githubusercontent.com/719962/217119209-ed283b01-93db-4a67-80ca-5f52425aa8ba.png)

### Information

  - Linux distro: Ubuntu 
  - Distro version: "Ubuntu 22.04.1 LTS"
  - Docker Desktop Version: 4.16.2 (95914)

### Steps to reproduce the behavior
As above in *Actual behavior*

**Comment by pjgoodall** [comment]
There is no task-bar in Ubuntu.

**Comment by pjgoodall** [comment]
OK found icon in task-bar - top-right of ubuntu screen.

**Comment by rossjrw** [comment]
Noting that on recent GNOME versions, this menu does not exist, but a legacy version can be installed via https://extensions.gnome.org/extension/615/appindicator-support/
