### ISSUE TITLE
Incompatibility with Ubuntu 22.04 when running Docker with Ubuntu 20.04

### ISSUE THREAD

**Issue by nav9** [docker/desktop-linux#121]
The reference question is [here](https://softwarerecs.stackexchange.com/questions/85173/reliable-free-and-open-source-container-engine-truly-operating-system-agnostic).   
To reproduce the problem, I believe you just need to create a Docker container which uses Ubuntu 20.04, and that Docker container should build NGINX and Kafka. The Docker container should be run on an AWS EC2 instance which runs Ubuntu 22.04.  
  
**The issue I'm reporting by itself is not the problem. The problem is that Docker does not seem to serve the purpose it was meant to serve. To be able to seamlessly run on various operating systems, regardless of the version or perhaps even the hardware architecture. Please mention this to the system architects in charge of Docker.**

**Comment by nav9** [comment]
Nobody is bothered about this?

**Comment by vgadev** [comment]
This appears to still be a problem. Any chance it will get some attention.

/remove-lifecycle stale
/lifecycle frozen

**Comment by nav9** [comment]
@vgadev: Perhaps it would help to open a new issue and link it to this issue. The Docker team is probably not going to look into this issue since it is closed. They probably allowed it to be closed because they thought only I encountered this issue. But it looks like it is a much more fundamental issue with the very foundations of Docker...as in Docker not fulfilling the very purpose for which it was built.
