### ISSUE TITLE
debian package of docker-desktop leaves arch linux files (pkgbuild, package.install file, etc.) (and fedora spec file) in root directory

### ISSUE THREAD

**Issue by ANeilan** [docker/desktop-linux#123]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 77aedea9-b10f-4ae1-9c66-198829326065/20230216021224

not sure these apply since the issue is with miscellaneous files included in the debian package

### Expected behavior
Not have miscellaneous files in the root directory
### Actual behavior
Arch Linux package files and fedora spec file are in the root directory
### Information

  - Linux distro: Debian
  - Distro version: Debian Sid/Unstable
  - Docker Desktop Version: 4.16.2-95914

### Steps to reproduce the behavior

  1. Install docker-desktop (.deb) package
  2. `dpkg -L docker-desktop|head`
  ![image](https://user-images.githubusercontent.com/12475765/219248033-11063fc7-d0a7-49fc-8b8e-94576a24402e.png)
  3. ?
  4. Profit

**Comment by aiordache** [comment]
@ANeilan Thank you for raising this issue and sorry for it. The package should be clean with the next release 4.17
