### ISSUE TITLE
Docker Desktop Extension failed to install on Arch version

### ISSUE THREAD

**Issue by jawadan** [docker/desktop-linux#127]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Linux distro: Manjaro
  - Distro version: 
  - Docker Desktop Version: 4.17

### Steps to reproduce the behavior

I am getting an error when I am trying to install extension on Docker Desktop 4.17 Arch version. Other than that everything work smoothly. Here is the massage Docker Desktop is showing:

Failed to install extension: installation could not be completed due to: rename /tmp/1024156731-ext-install/mutagenio_docker-desktop-extension /home/jawa/.docker/desktop/extensions/mutagenio_docker-desktop-extension: invalid cross-device link

Please help. It feels like I got so close to make it work properly on my host.

**Comment by wsouto** [comment]
I'm on Fedora 37 (clean install) default filesystem is BTRFS (not sure if it is related) having the same issue.

**Comment by rossjrw** [comment]
Also experiencing this on Fedora 37.

**Comment by alebarra** [comment]
Also in Ubuntu 22.04.2 LTS, it is not possible to install any type of extension.

- Docker Compose version v2.15.1
- Docker version 23.0.1, build a5ee5b1

- **Client: Docker Engine - Community**
 Cloud integration: v1.0.31
 Version:           23.0.1
 API version:       1.41 (downgraded from 1.42)
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           desktop-linux

- **Server: Docker Desktop 4.17.0 (99724)**
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:32:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by rossjrw** [comment]
/remove-lifecycle stale

Still experiencing this issue on Fedora 38.

**Comment by rossjrw** [comment]
/lifecycle frozen

There's no reason for this issue to self-close without being addressed by a Docker developer.

**Comment by benja-M-1** [comment]
Hi @rossjrw, @wsouto, @jawadan I am working on the extensions. What version of Docker Desktop are you using? This should be fix from Docker Desktop 4.18.

**Comment by rossjrw** [comment]
@benja-M-1  4.17.0. After updating to 4.20.1 I can confirm that extension installation works as expected on Fedora 38 at least.

That I assumed I was on the latest version is embarrassing, honestly. Thanks for letting us know that this is already fixed.

**Comment by benja-M-1** [comment]
Glad to read that! I am sorry for the late response.
I will close this issue, feel free to reopen if it still fails for version >= 4.18.
