### ISSUE TITLE
[Request] .zst packages in official / AUR

### ISSUE THREAD

**Issue by yozachar** [docker/desktop-linux#14]
https://docs.docker.com/desktop/linux/install/archlinux/

Please provide ArchLinux package on official / AUR repository.

**Comment by AmauryOrtega** [comment]
Careful attention to users that have docker-scan and docker-compose installed already on Arch.

```shell
export VERSION=4.8.2
wget https://desktop.docker.com/linux/main/amd64/docker-desktop-"$VERSION"-x86_64.pkg.tar.zst
sudo pacman -U "./docker-desktop-"$VERSION"-x86_64.pkg.tar.zst"

docker-desktop: /usr/lib/docker/cli-plugins/docker-compose exists in filesystem (owned by docker-compose)
docker-desktop: /usr/lib/docker/cli-plugins/docker-scan exists in filesystem (owned by docker-scan)
```

**Comment by creio** [comment]
@AmauryOrtega `sudo pacman -U ./docker-desktop-<version>-<arch>.pkg.tar.zst --overwrite='*'`

**Comment by bulletmark** [comment]
@AmauryOrtega yes, Arch users should not be forcing overwrites like that. The docker-desktop Arch package presently can not co-exist with the docker-compose package. The clash should be fixed so that both can be installed in parallel. Until that is fixed, a `conflicts=("docker-compose")` line should probably be added to the docker-desktop `PKGBUILD`. Ultimately docker-desktop should be added to the AUR so that package is easily discoverable and so users get automatic updates etc.

**Comment by dylanmtaylor** [comment]
> https://docs.docker.com/desktop/linux/install/archlinux/
> 
> Please provide ArchLinux package on official / AUR repository.

Alternatively, would be nice if we had an official docker repo we could add to pacman.conf and get automatic updates that way.

**Comment by Srish-ty** [comment]
> @AmauryOrtega `sudo pacman -U ./docker-desktop-<version>-<arch>.pkg.tar.zst --overwrite='*'`

Thank uh. overwriting actually helped. i was getting conflicts error :conflicting files:
- docker-desktop: /usr/lib/docker/cli-plugins/docker-compose already exists in filesystem (owned by docker-compose)

but 
sudo pacman -U ./docker-desktop-4.18.0-x86_64.pkg.tar.zst --overwrite='*'

helped

**Comment by Srish-ty** [comment]
> https://docs.docker.com/desktop/linux/install/archlinux/
> 
> Please provide ArchLinux package on official / AUR repository.

`sudo pacman -U ./docker-desktop-4.18.0-x86_64.pkg.tar.zst --overwrite='*'
`

**Comment by killertofus** [comment]
bump
