### ISSUE TITLE
Docker Desktop will not start Docker engine on Ubuntu 22.04

### ISSUE THREAD

**Issue by orionthewake** [docker/desktop-linux#142]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 381084be-d487-4593-9ebc-04f0744db019/20230419130501

### Expected behavior

Docker engine starts.

### Actual behavior

Docker engine does not start.

### Information

  - Linux distro: Ubuntu
  - Distro version: 22.04.2 LTS
  - Docker Desktop Version: 4.18.0

After upgrading to Docker Desktop 4.18.0 from 4.16.2, the Docker Engine will not start when starting Docker Desktop. The "Starting Docker Engine..." message just spins continuously. See screenshot.

This is reproducible even after rebooting the laptop. This is on a native installation of Ubuntu 22.04.2 LTS on a Thinkpad Gen 9.

### Steps to reproduce the behavior
1. Install latest Docker Desktop 4.18.0 over 4.16.2 using `sudo apt install ./docker-desktop-4.18.0-amd64.deb`
2. Reboot native installation of Ubuntu 
3. After logging in, click Docker Desktop icon

![image](https://user-images.githubusercontent.com/6590854/233085437-7c2dbc3c-0593-4214-854b-b50b404d9911.png)

**Comment by dcopso** [comment]
I have similar symptoms. Docker Desktop for Linux on Ubuntu 22.04 just hangs here:

![image](https://user-images.githubusercontent.com/103620283/233539420-4fa17564-3eb6-418d-a446-ca740efa7005.png)

Diagnostic ID: `b5c307bc-6520-45ae-ac63-c16b3331948d/20230421040856`

I've confirmed my user is in the kvm group and rebooted.

```
$ /opt/docker-desktop/bin/com.docker.diagnose check
[PASS] DD0039: are KVM user permissions configured?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[FAIL] DD0017: can a VM be started? vm has not started: failed to open kmsg.log: open /home/USERNAME/.docker/desktop/log/vm/kmsg.log: no such file or directory
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: failed to open kmsg.log: open /home/USERNAME/.docker/desktop/log/vm/kmsg.log: no such file or directory
...
[FAIL] DD0031: does the Docker API work? Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?
...
Cannot connect to the Docker daemon at unix:///home/USERNAME/.docker/desktop/docker.sock. Is the docker daemon running?

...
[FAIL] DD0014: are the backend processes running? 3 errors occurred:
	* querying com.docker.backend process: is it running as a different user?: readlink /proc/2534/exe: permission denied
	* qemu-system-x86_64 is not running
	* com.docker.driver.amd64-linux is not running
...
Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: failed to open kmsg.log: open /home/USERNAME/.docker/desktop/log/vm/kmsg.log: no such file or directory
```

Thanks.

**Comment by aiordache** [comment]
@dcopso The diag bundle you uploaded shows a missing configuration needed for the filesharing:
```
[E] setting up ID maps for virtiofsd namespace: retrieving subordinate UID range: opening /etc/subuid: open /etc/subuid: no such file or directory
```
Please check [the documentation](https://docs.docker.com/desktop/faqs/linuxfaqs/#how-do-i-enable-file-sharing) on how to set up the id mapping files.

@orionthewake I can not spot a clear cause for your failure from the diag bundle that you uploaded. Do you get the same behaviour if you upgrade to 4.19? Can you try that and upload a new bundle please?

**Comment by orionthewake** [comment]
@aiordache Thank you! I had no issues after upgrading to 4.19.0.
