### ISSUE TITLE
docker cp get error" can't add XXXX to tar: archive/tar:write too long"

### ISSUE THREAD

**Issue by michelle-chou25** [docker/desktop-linux#146]
docker cp consolidated.00.pth test_alpaca:/home/model_zoo/llama/7B
ERRO[0000] Can't add file /home/michellezhou/llama/7B/consolidated.00.pth to tar: archive/tar: write too long

  - [ ] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 0000

  - Linux distro: inux version 3.10.0-1160.49.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Nov 30 15:51:32 UTC 2021
  - Distro version:
  - Docker Desktop Version:20.10.17
I'm running into this issue in a newer docker version:
Client: Docker Engine - Community
Version: 20.10.12
API version: 1.41
Go version: go1.16.12
Git commit: e91ed57
Built: Mon Dec 13 11:45:41 2021
OS/Arch: linux/amd64
Context: default
Experimental: true

Server: Docker Engine - Community
Engine:
Version: 20.10.17
API version: 1.41 (minimum version 1.12)
Go version: go1.17.11
Git commit: a89b842
Built: Mon Jun 6 23:03:33 2022
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.4.12
GitCommit: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
runc:
Version: 1.0.2
GitCommit: v1.0.2-0-g52b36a2
docker-init:
Version: 0.19.0
GitCommit: de40ad0

### Steps to reproduce the behavior
<!--
A reproducible case, Dockerfiles FTW.
I run the cp command:
the size of the .pth file is 12.2G 
docker cp consolidated.00.pth test_alpaca:/home/model_zoo/llama/7B
ERRO[0000] Can't add file /home/michellezhou/llama/7B/consolidated.00.pth to tar: archive/tar: write too long

**Comment by aiordache** [comment]
Hi @michelle-chou25. This does not seem a Docker Desktop use case but a Docker CLI/Engine installed on the host. Perhaps the https://github.com/docker/cli issue tracker would be the best place to raise this issue.
