### ISSUE TITLE
Docker Desktop closes if opened twice

### ISSUE THREAD

**Issue by peshkopy** [docker/desktop-linux#148]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 145e6eb2-6bbc-4fef-8f18-085918ca8abe/20230513155116

### Expected behavior
Open the Docker Desktop application by clicking on the desktop icon, even if the application has already been launched.

### Actual behavior
The Docker Desktop application closes by clicking on the desktop icon if the application has already been launched, and cannot be restarted by clicking the desktop icon again.
Only Docker Desktop application is affected, not the docker engine part.

Log error : `com.docker.backend[5216]: [2023-05-13T15:17:24.376171420Z][com.docker.backend][I] electron shutdown by signal: killed`

### Information

  - Linux distro: Ubuntu
  - Distro version: 22.04.2 LTS
  - Docker Desktop Version: 4.19.0 (not before)

### Steps to reproduce the behavior

  1. Open the Docker Desktop application by clicking on the desktop icon or /opt/docker-desktop/bin/docker-desktop in command line
  2. Renew 1

**Comment by shubh402** [comment]
any update?

**Comment by peshkopy** [comment]
Same problem on latest version 4.22.0

**Comment by shubh402** [comment]
> Same problem on latest version 4.22.0

yeah, I thought it's my window manager at first but then I saw this issue

**Comment by mmrkvkn** [comment]
same problem

**Comment by lorenrh** [comment]
Hi there, would you mind installing the latest version of Docker Desktop (4.22.1) and see if the problem is still there?

**Comment by shubh402** [comment]
> Hi there, would you mind installing the latest version of Docker Desktop (4.22.1) and see if the problem is still there?

fixed, atleast on my machine

**Comment by mmrkvkn** [comment]
not fixed

**Comment by peshkopy** [comment]
Same problem on latest version 4.22.1

**Comment by ghost** [comment]
Same problem on  4.22.1 version

**Comment by lorenrh** [comment]
We've release Docker Desktop 4.23, containing a fix for this issue. Would you mind checking that out? 

https://docs.docker.com/desktop/release-notes/

**Comment by ghost** [comment]
Fixed in `2.23.0 ` version. Works as expected for me.

**Comment by peshkopy** [comment]
Fixed on 4.23.0 version, thank you !
