### ISSUE TITLE
Docker menu isn't available on Gnome 3

### ISSUE THREAD

**Issue by joel0** [docker/desktop-linux#16]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 041543a3-56f1-491d-9f23-7b132ea2bb23/20220512201532

### Expected behavior
I expect to be able to find the "Docker menu" somewhere to be able to pause and quit Docker Desktop.

### Actual behavior
Without third-party Gnome extensions (such as [Tray Icons: Reloaded](https://extensions.gnome.org/extension/2890/tray-icons-reloaded/)), my only option to quit or restart Docker Desktop is by using `systemctl --user ...` from a terminal.

### Information
  - Linux distro: Debian
  - Distro version: 11
  - Docker Desktop Version: 4.8.1-78998

By default, Gnome 3 does not provide access to tray icons.  This leads to problems when trying to follow instructions, such as [Pause/Resume](https://docs.docker.com/desktop/linux/#pauseresume).  It also makes it impossible, to my knowledge, to stop Docker Desktop from the GUI.

Since there's no tray icon, I'd almost expect closing the Docker Desktop window to quit Docker Desktop, rather than leaving it running.  Beyond that, I'd think the "Docker menu" must be put somewhere inside the main window when there's no system tray area.

### Steps to reproduce the behavior
  1. Do a fresh install of any distro that uses plain Gnome 3+ as the DE.  e.g. Debian 11, Fedora, and possibly Ubuntu?
  2. Install Docker Desktop and open it.
  3. Attempt to pause or stop Docker Desktop from the GUI.  There's no option.

**Comment by p1-0tr** [comment]
@joel0 thanks for reporting this issue. Currently we document the requirement for having a gnome extension to support tray icons, but we are also working on a better solution in order to drop that requirement.

**Comment by joel0** [comment]
@p1-0tr Perhaps the requirement should also be mentioned in the [system requirements] (https://docs.docker.com/desktop/linux/install/#system-requirements) list.  I hadn't even looked at the instructions where the requirement is currently documented, which is why I was confused.

**Comment by p1-0tr** [comment]
@joel0 thanks, good point :)

**Comment by joel0** [comment]
Thanks @p1-0tr !  Since this is not a bug and seems to be tracked elsewhere, I'll close this issue.
