### ISSUE TITLE
Install instructions for ubuntu missing a line

### ISSUE THREAD

**Issue by aiqc** [docker/desktop-linux#160]
### Description

As described in this highly upvoted [answer](https://stackoverflow.com/a/73455413/5739514), the final line of `sudo apt update -y` is missing from the [installation instructions](https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository) about setting up the repository.

Without running that step, the deb package won't install
```
$ sudo apt-get install ./docker-desktop-4.21.1-amd64.deb 

The following packages have unmet dependencies:
 docker-desktop : Depends: docker-ce-cli but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Ubuntu 22.04

I've done this on 3 separate systems now

### Reproduce

follow the installation instructions about setting up the repo

### docker version

```bash
docker-desktop-4.21.1-amd64.deb
```

### docker info

```bash
docker-desktop-4.21.1-amd64.deb
```

### Diagnostics ID

ID

**Comment by aevesdocker** [comment]
Thanks for raising the issue @aiqc! This has now been fixed in docs.
