### ISSUE TITLE
Docker Desktop launch error: waiting for qemu process

### ISSUE THREAD

**Issue by that-one-arab** [docker/desktop-linux#162]
### Description

I ran a fresh install on a different machine with ubuntu using the steps mentioned [here](https://docs.docker.com/desktop/install/ubuntu/)

After choosing Docker Desktop from my Applications list, I get the below error

![image](https://github.com/docker/desktop-linux/assets/91668821/6022b1cc-c9bc-4a51-bd60-380922c56aa4)

### Reproduce

1. Install on ubuntu 22.04 using steps mentioned [here](https://docs.docker.com/desktop/install/ubuntu/)
2. Click on Ubuntu Desktop from Applications

### docker version

```bash
Client: Docker Engine - Community
 Cloud integration: v1.0.35
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:18 2023
 OS/Arch:           linux/amd64
 Context:           default
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     /usr/lib/docker/cli-plugins/docker-scout

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

### Diagnostics ID

484b0706-ff4b-4a97-bcdd-9167cc587a19/20230731162048

### Additional Info

I already tried reinstalling docker using steps mentioned in the same installation page

**Comment by aiordache** [comment]
Hi @that-one-arab. You are missing virtualization support:
```
[com.docker.backend.qemu][I] Could not access KVM kernel module: No such file or directory
[com.docker.backend.qemu][I] qemu-system-x86_64: -accel kvm: failed to initialize kvm: No such file or directory
```
Check system requirements on how to check and enable it: https://docs.docker.com/desktop/install/linux-install/#system-requirements

**Comment by that-one-arab** [comment]
That was correct. For some reason KVM support was not enabled in my BIOS by default. I enabled it from my computer's BIOS configuration. Thank you!

**Comment by BuildWithLal** [comment]
i was running Virtualbox at the same time and was getting same error from docker desktop launch. Once i closed Virtualbox, docker desktop started working.

**Comment by HectorLH** [comment]
Same issue, but enabling KVM support in BIOS doesnt solve the problem.
