### ISSUE TITLE
stuck at error while running docker build command

### ISSUE THREAD

**Issue by leamandeep** [docker/desktop-linux#172]
### Description

I was trying to build an image for my Node app.  But I'm stuck at this error on running the build command. All my docker commands are working properly.

>Here's my dockerfile
```
FROM node:20

COPY package.json /app/
COPY src /app/

WORKDIR /app

RUN npm install

CMD [ "node" , "server.js"]
```

> Here's the error. Rn I'm stuck at.

```
[internal] load metadata for docker.io/library/node:20:
------
Dockerfile:1
--------------------
   1 | >>> FROM node:20
   2 |     
   3 |     COPY package.json /app/
--------------------
ERROR: failed to solve: node:20: error getting credentials - err: exit status 1, out: `error getting credentials - err: exit status 1, out: `exit status 2: gpg: decryption failed: No secret key``
```

### Reproduce

docker -t node-app:1.0  .

### Expected behavior

It should build docker image of my node app

### docker version

```bash
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Client: Docker Engine - Community
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:44 2023
 OS/Arch:           linux/amd64
 Context:           default
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.1
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2-desktop.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     /usr/lib/docker/cli-plugins/docker-scout

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

### Diagnostics ID

24f767bb-efd2-4b18-afd2-5bca2d5323c3/20231008153001

### Additional Info

When i run docker version command. I'm getting errors.
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Comment by leamandeep** [comment]
Any update on this issue?

**Comment by leamandeep** [comment]
@bsousaa  any update on this issue?

**Comment by anhwrkspx** [comment]
It seem like your docker is not running. What is your OS : Mac or Windows ? 
I suggest:

1.  Start Docker daemon from this guide:
- For Window:   https://stackoverflow.com/questions/44169435/how-to-start-the-docker-daemon
- For Mac/Ubuntu:  sudo systemctl start docker
2. Authenticate for Docker

Let me know if anything go wrong

**Comment by leamandeep** [comment]
> It seem like your docker is not running. What is your OS : Mac or Windows ? I suggest:
> 
>     1. Start Docker daemon from this guide:
> 
> 
>     * For Window:   https://stackoverflow.com/questions/44169435/how-to-start-the-docker-daemon
> 
>     * For Mac/Ubuntu:  sudo systemctl start docker
> 
> 
>     2. Authenticate for Docker
> 
> 
> Let me know if anything go wrong

After installing a new version of docker, Everything is working great
