### ISSUE TITLE
Installing deb has error Dependency is not satisfiable: docker-ce-cli

### ISSUE THREAD

**Issue by sharpsteelsoftware1** [docker/desktop-linux#21]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

When I run the Docker for Linux .deb then software manager should allow me to install the package.

### Actual behavior

Software manager (DEB installer on Mint) has an error that says "Error: Dependency is not satisfiable: docker-ce-cli"

### Steps to reproduce the behavior

Linux Mint 20.3 Cinnamon
Latest docker DEB from https://docs.docker.com/desktop/linux/install/

**Comment by tnhkit** [comment]
+1

**Comment by juliaradula** [comment]
+1

**Comment by p1-0tr** [comment]
@tnhkit and @juliaradula did you follow step 1 from https://docs.docker.com/desktop/linux/install/ubuntu/#install-docker-desktop (which links to https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository)?

**Comment by juliaradula** [comment]
> @tnhkit and @juliaradula did you follow step 1 from https://docs.docker.com/desktop/linux/install/ubuntu/#install-docker-desktop (which links to https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository)?

I tried that before, but didn't work. Thanks

**Comment by thursdaybw** [comment]
The very first thing this doc says is download the deb.

https://docs.docker.com/desktop/linux/install/

That page is misleading, see https://docs.docker.com/desktop/linux/install/ubuntu/ instead.

**Comment by p1-0tr** [comment]
The docs has been improved to make the per-distro install steps more prominent  - https://docs.docker.com/desktop/install/linux-install/
