### ISSUE TITLE
Is it possible to connect to docker socket / docker engine API from host machine without using docker-cli?

### ISSUE THREAD

**Issue by christianfosli** [docker/desktop-linux#23]
I would like to use Docker integration in the JetBrains Rider editor, however I can't get it to work since there is no unix socket for docker on my host machine. It presumably only exists in the VM.

![image](https://user-images.githubusercontent.com/36294671/170461130-14d719c4-62b9-4f02-b0f1-f47b39ee23ec.png)

See-also: https://youtrack.jetbrains.com/issue/RIDER-77609/Cannot-connect-to-the-Docker-daemon-at-Unix-socket-Docker-Deskto

---

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
 
### Expected behavior

There should be a unix socket available on /var/run/docker.sock on my host filesystem, or there should be some documentation about how to connect to docker engine API over TCP (URL/ports..).

### Actual behavior

There is no unix socket on /var/run/docker.sock on my host filesystem, and I'm unable to figure out how to connect to docker engine API from my host computer over TCP (URL/ports..).

### Information

  - Linux distro: Fedora Linux
  - Distro version: 36
  - Docker Desktop Version: 4.8.2 (79419)

**Comment by christianfosli** [comment]
Hehe, just after writing this issue I tried

```bash
docker context ls
```

Which showed be that the docker desktop endpoint was available at `$HOME/.docker/desktop/docker.sock`.
I can successfully call it with curl like so:

```bash
curl --unix-socket $HOME/.docker/desktop/docker.sock http://localhost/version
```
.

Closing since I answered my own question :sweat_smile:

**Comment by SIMULATAN** [comment]
Thanks for this command!
I'm using docker for quarkus and couldn't find how to specify the docker daemon location, so I just symlinked the path that `docker context ls` spit out to `/var/run/docker.sock` and it seems to work :tada:
