### ISSUE TITLE
Docker-desktop cannot start virtiofsd

### ISSUE THREAD

**Issue by jqcui1999** [docker/desktop-linux#231]
### Description

Starting Docker-desktop reports the following error：
"running engine: waiting for the VM setup to be ready: running filesharing: running virtiofsd for /home: exit status 127"
![image](https://github.com/user-attachments/assets/c8c93660-7462-4c7d-9af4-fd6c6cc46fc7)

### Reproduce

1. Start by clicking the docker-desktop icon from the launcher
2. Reports virtiofsd related errors and cannot be started

### Expected behavior

Run docker-desktop normally

### docker version

```bash
Client:
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:01:25 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:03:05 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    27.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     /usr/local/lib/docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.14
    Path:     /usr/local/lib/docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /usr/local/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.10.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.28-01-perlis001-5
 Operating System: DingOS 0.8 (ding-perlis-minsky-v50)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.41GiB
 Name: Ding-Perlis-MP26JBT0
 ID: 758e7a8f-1c25-4da2-9fc6-857d0f86db6b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Diagnostics ID

D3BA4F44-F7A1-4753-A84D-40EF03CEF6EE/20240724071654

### Additional Info

1. My system information

> Linux distro: LFS
> Distro version: Refer to the LFS documentation to build my own system。
> Desktop:
> KDE Plasma (5.27.5)
> KDE application framework version (5.106.0)
> Qt: 5.15.10
> Kernel  (6.6.28)
> Graphics Platform: Wayland
> Qemu Version: 7.1.0
> Kvm Platform: kvm_intel
> Docker Desktop Version: 4.32.0

3. Installing docker-desktop without using a package manager：

> a. I downloaded the installation package of docker-desktop for debian
> b. Get the data.tar.xz and control.tar.xz files by unpacking docker-desktop-amd64.deb
> c. Unzip the data.tar.xz file and copy it to the system root directory using command `cp -ra`.
> d. Unzip control.tar.xz and manually execute the script.

4. System Background：
My operating system is built by myself and there is no build package manager, so I installed docker-desktop in the form of binary file copy, but I encountered this problem.

I hope you can give me some suggestions for solutions. Thank you.

**Comment by jqcui1999** [comment]
When I follow the Ubuntu installation manual to install docker-desktop for my kde ubuntu, it still doesn't work.

**Comment by doringeman** [comment]
Hello,

Have you followed the steps from https://docs.docker.com/desktop/faqs/linuxfaqs/#how-do-i-enable-file-sharing?
Can you make sure the intervals entries in `/etc/subuid` and `/etc/subgid` don't overlap?

**Comment by jqcui1999** [comment]
> Hello,
> 
> Have you followed the steps from https://docs.docker.com/desktop/faqs/linuxfaqs/#how-do-i-enable-file-sharing? Can you make sure the intervals entries in `/etc/subuid` and `/etc/subgid` don't overlap?

Hi,
I don't quite understand what you mean, but the contents of my file are as follows:
```
$cat /etc/subuid 
cuijq:100000:65536
$ cat /etc/subgid 
cuijq:100000:65536
```
Does it mean that the IDs of these two files should not be the same and need to be segmented? For example, I set subuid to 100000:35536 and subgid to 135537:20000?

**Comment by doringeman** [comment]
They look good, it's fine. I meant the entries in the same file shouldn't overlap.

I found the issue, you're missing `libseccomp`.
```
/opt/docker-desktop/bin/virtiofsd: error while loading shared libraries: libseccomp.so.2: cannot open shared object file: No such file or directory
```
Can you install it and try again?

**Comment by jqcui1999** [comment]
Thank you for your help.
After I completed the dependencies, the virtiofsd exception problem no longer reappeared, but I encountered a new problem. When I started docker-desktop, I could not start the docker engine through the new context desktop-linux. I don't know why this happened. The 'docker context ls' command shows that it has switched to the context desktop-linux. The following is my error and the uploaded diagnostic log ID.
```
The diagnostic log ID：
"3F114BDA-E041-4B3F-AF25-ADE9699F35B9/20240730103707".
The error:
running engine: waiting for the Docker API: context deadline exceeded
```

**Comment by doringeman** [comment]
Do you have `/etc/ssl/certs/ca-bundle.crt` on your host?

**Comment by jqcui1999** [comment]
> Do you have `/etc/ssl/certs/ca-bundle.crt` on your host?

Thank you very much. My ca-bundle.crt is in the '/etc/pki/tls/certs/' directory. I created a soft link and solved the problem. Thank you again.

**Comment by doringeman** [comment]
You're welcome! :)
