### ISSUE TITLE
error getting credentials no usernames for https://index.docker.io/v1/

### ISSUE THREAD

**Issue by endersonmaia** [docker/desktop-linux#25]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 585a1352-38a8-46b7-b724-48ec29421b9d/20220602190247

### Expected behavior

The build should run without issue, docker compose up should run without issues.

### Actual behavior

The build fails to download the images I still don't have locally.

### Information

  - Linux distro: Ubuntu
  - Distro version: 20.04
  - Docker Desktop Version: Docker version 20.10.16, build aa7e414

### Steps to reproduce the behavior

If I reset to factory, everything works.

After I login to my account, any build or compose up command will fail to download images that are not downloaded yet.

**Comment by aiordache** [comment]
Hi @endersonmaia 
The diagnostics logs show an error when trying to store the credentials:
```
adding access token to store: error storing credentials - err: exit status 1, out: `exit status 1: gpg: ...: There is no assurance this key belongs to the named user
gpg: cannot open '/dev/tty': No such device or address
Password encryption aborted.`
```
Can you check please the gpg setup, test if you can encrypt a file, then try manually to store a password with `pass`?

**Comment by endersonmaia** [comment]
> There is no assurance this key belongs to the named user

Does the gpg key needs to have the same e-mail for the Docker Hub user ? 

If yes, that's the problem, I will test and report here.
