### ISSUE TITLE
Containers get unmatching IP addresses

### ISSUE THREAD

**Issue by Paoloooooo** [docker/desktop-linux#256]
### Description

I recently noticed that when I run a container or a devcontainer, they get an ip that is different from the host one. I am running them with the flag `--net=host`, but they still have different IPs.
Just as example I'll describe what I saw today. I am using a static ip for a project and the host ip was `192.168.0.10`. I started a webserver in a devcontainer using Flask and it was reachable to the IP `192.168.0.9`.

I'm trying to understand why I get these different IPs but I couldn't find anything in docker desktop settings or configuration to help me.

Note that all the containers use the same ip, so it's like they are on a virtual network.

### Reproduce

docker run --net=host --volume=$HOME/$WS:/root/$WS --name pepper_ros_cnt -it pepper_ros

### Expected behavior

When running the containers with `--net=host` or `--network=host` they should share the same ip as the host machine.

### docker version

Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:03 2024
 OS/Arch:           linux/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.34.3 (170107)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### docker info

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     /usr/lib/docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /usr/lib/docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /usr/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     /usr/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 6
 Server Version: 27.2.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.4-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 13.4GiB
 Name: docker-desktop
 ID: f5d443a2-7299-442b-b800-af2640bfc4e2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///home/paolo/.docker/desktop/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile

### Diagnostics ID

1D947B57-D711-46FB-904A-2FB49FF778B1/20241105223857

### Additional Info
These are the output of some maybe useful commands:

```
> docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
16208458c241   bridge    bridge    local
560f097413a9   host      host      local
8d8f04c7f28d   none      null      local

> docker network inspect 16208458c241
[
    {
        "Name": "bridge",
        "Id": "16208458c241a9eca273fbc702080c5ffe46fab71b762d3b50070b2cda01226f",
        "Created": "2024-11-05T22:54:13.430635014Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

> docker network inspect 560f097413a9
[
    {
        "Name": "host",
        "Id": "560f097413a9f3e68f341b0b13d5fd49175b3dca9d49c3f592d65275e57ead60",
        "Created": "2024-11-03T14:30:11.600830823Z",
        "Scope": "local",
        "Driver": "host",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": null
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]

> docker network inspect 8d8f04c7f28d
[
    {
        "Name": "none",
        "Id": "8d8f04c7f28d45a90d3204a62a2c2040c3634930e64a157a7f119375da1c2add",
        "Created": "2024-11-03T14:30:11.55644968Z",
        "Scope": "local",
        "Driver": "null",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": null
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
```

**Comment by jpbriend** [comment]
Hi @Paoloooooo ,
`host-networking` option is not enabled in Docker Desktop settings.
You can enable it by going to `Settings` - `Resources` - `Network`. The option is named `Enable host networking`.

Tick the checkbox and hit `Apply & Restart`. It should work as expected after this setting is enabled.

**Comment by Paoloooooo** [comment]
Hi @jpbriend,
I have toggled that option in the past, but it keeps disappearing. It could be related to the fact that I get kicked out from my Docker account almost each time I close and reopen Docker Desktop.

Is there a way to automatically toggle this setting, maybe in the terminal? If there is such an option I could simply run those commands at the startup and have it fixed.

**Comment by jpbriend** [comment]
Would you mind upgrading to [4.35.1](https://docs.docker.com/desktop/release-notes/#4351) ?
In this version we removed the requirement to be signed in to have host-networking work.

It's weird you get signed out when you close Docker Desktop.
Can you generate a new diagnostic right after restarting Docker Desktop if you are signed out? (the logs will contain the moment you've been signed out when closing or at startup). I will have a look at it.

**Comment by Paoloooooo** [comment]
Here is the new diagnostics ID: 1D947B57-D711-46FB-904A-2FB49FF778B1/20241106103607.

I am also upgrading to the newer version, I'll let you know if that fixes the problem.

**Comment by jpbriend** [comment]
It seems your credentials are not stored in your native key store.
Can you make sure you correctly initialized `pass`, as indicated in [this documentation](https://docs.docker.com/desktop/get-started/#signing-in-with-docker-desktop-for-linux)?

**Comment by Paoloooooo** [comment]
I followed that tutorial and upgraded to the newest version, but I still have both the problems. This is the new diagnostics ID: 1D947B57-D711-46FB-904A-2FB49FF778B1/20241106125246

Maybe I can try to reset to fabric settings, this should just clear the settings, am I right?

**Comment by jpbriend** [comment]
Reset to factory settings will also clear the VM disk, which means the Docker cache will go away.

**Comment by Paoloooooo** [comment]
I just reset it, but it is still giving me the IP problem. Now the IP it gives me comes from the subnet specified in docker setting: `192.168.65.0/24`(I am still running the containers with the `--net=host` flag). Do you know if there is a way to ignore that setting under the Settings -> Resources -> Network tab?

**Comment by akerouanton** [comment]
Hey @Paoloooooo,

Thanks for reporting. I'm a bit confused about what's going on and will need some clarification so that I fully capture the situation.

> I recently noticed that when I run a container or a devcontainer, they get an ip that is different from the host one. I am running them with the flag --net=host, but they still have different IPs.
Just as example I'll describe what I saw today. I am using a static ip for a project and the host ip was 192.168.0.10. I started a webserver in a devcontainer using Flask and it was reachable to the IP 192.168.0.9.

> but it is still giving me the IP problem.

Are you still facing the same issue as you described in your original report? Or did resetting DD solved the issue you described initially?

If you're still facing it, could you confirm that your flask webserver was started on `0.0.0.0` in your `--net=host` container, and it was unexpectedly accessible from `192.168.0.9` instead of `192.168.0.10`?

If this description isn't accurate, could you describe what `192.168.0.9` and `192.168.0.10` are? Like, is this two IP addresses attached to your host? (and also confirm on which IP address flask is listening on)

> Now the IP it gives me comes from the subnet specified in docker setting: 192.168.65.0/24(I am still running the containers with the --net=host flag).

So, you send a request to your webserver from your linux host, and flask sees the request is coming from `192.168.65.1`, although you expect it to come from `127.0.0.1`. Is this causing any sort of issue, or is it just an annoyance? If it's causing issues, could you describe them please?

This behavior is currently correct as per the code, although I agree it might be surprising. Basically, on DD host networking works by watching socket-related events and transparently creating port bindings between the host and the VM. This probably owes to be better documented. We could consider intercepting packets before they're delivered to the application to rewrite the source / dest addrs but we'd need to understand which real-world issue it solves.

**Comment by Paoloooooo** [comment]
Hi @akerouanton,
here are my answers, hope they'll help you.

`Are you still facing the same issue as you described in your original report? Or did resetting DD solved the issue you described initially?`
    - Yes, I'm still facing an issue but it doesn't seem the same of before. Now Flasks reports to be running on the address '192.168.65.9:7000' which isn't reachable. The website is instead reachable from the host IP, that is `192.168.0.10:7000/`. Is this an anomalous behaviour or is Flask supposed to do that when running in a container?

`Is this causing any sort of issue, or is it just an annoyance? If it's causing issues, could you describe them please?`
    - As of now the Flask bug seems to have disappeared, the only thing that still bothers me is that I can't share ROS connection between my host device and my containers. Since they have different IP I'm trying to understand what I can do to join the networks, but now I don't know if this problem can be faced in this issue or if it's better to create another one.

**Comment by akerouanton** [comment]
> Yes, I'm still facing an issue but it doesn't seem the same of before. Now Flasks reports to be running on the address '192.168.65.9:7000' which isn't reachable. The website is instead reachable from the host IP, that is 192.168.0.10:7000/. Is this an anomalous behaviour or is Flask supposed to do that when running in a container?

Oh, I see now! I guess you're already launching Flask with `--host=0.0.0.0`. 

```
$ flask --app hello run --host=0.0.0.0
 * Serving Flask app 'hello'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.65.3:5000
Press CTRL+C to quit
```

Well, the port-mapping created transparently will bind `0.0.0.0` too on the host, but Flask tries hard to resolve `0.0.0.0` into sensical addresses that could be copy/pasted. When Flask does that, it only sees and reports the IP addresses that exists in the VM -- so none of your host's addresses. I took a look at how Flask does that (FWIW `getsockname` + a netlink call) and I don't think there's any way we could fix this.

> As of now the Flask bug seems to have disappeared, the only thing that still bothers me is that I can't share ROS connection between my host device and my containers. Since they have different IP I'm trying to understand what I can do to join the networks, but now I don't know if this problem can be faced in this issue or if it's better to create another one.

Yeah I think it'd be best to create a separate issue that details what you're trying to achieve.

**Comment by Paoloooooo** [comment]
Okay, thank you very much to both of you @akerouanton @jpbriend.

I've tested the application with the mismatching IP addresses and it seems to work with the host IP and not the one provided by Flask. 

If you don't need more info, I think I can also close this issue. Let me know

**Comment by akerouanton** [comment]
You welcome!

Let me close this issue, but feel free to open a new one for the other issue you're facing.
