### ISSUE TITLE
black windows after install 4.9

### ISSUE THREAD

**Issue by Kowiste** [docker/desktop-linux#29]
I just update Docker desktop to the latest 4.9, come from 4.8.2, the program looks to start fine, appear the screen with Docker desktop starting and in the moment that should appear the container the windows go black, so after reinstall it reboot, nothing works and I  have to come back to 4.8.2.

I'm with Ubuntu 20.04.4 LTS

**Comment by aiordache** [comment]
Hi Kowiste, 
Sorry for the bug. Could you try this build please and let us know if it fixes the issue? 
https://desktop-stage.docker.com/linux/main/amd64/80969/docker-desktop-4.9.0-amd64.deb

**Comment by Kowiste** [comment]
> Hi Kowiste, Sorry for the bug. Could you try this build please and let us know if it fixes the issue? https://desktop-stage.docker.com/linux/main/amd64/80969/docker-desktop-4.9.0-amd64.deb

Works perfect!!, but I still have the same problem with chmod [https://github.com/docker/desktop-linux/issues/9](url)

**Comment by SuperTalonMan** [comment]
I'm having the same issue on Windows 10 (Version 21H2 - Build 19044.1706) with Docker Desktop 4.9.0. Do you have a corresponding build with a fix for Windows?

**Comment by p1-0tr** [comment]
@SuperTalonMan - yup links have been posted here - https://github.com/docker/for-win/issues/12759 .
