### ISSUE TITLE
Docker Desktop don't start in Arch Linux

### ISSUE THREAD

**Issue by NashiraDeer** [docker/desktop-linux#32]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 72af8b25-03e7-4cbf-aee6-d5987f18dcf9/20220619100134

### Expected behavior

Docker Desktop runs

### Actual behavior

Docker Desktop freezes in "Starting" state.

### Information

This problem is new in Docker Desktop 4.9.x, when I used Docker Desktop 4.8.x it starts normally.

  - Linux distro: Arch Linux
  - Distro version: Rolling
  - Docker Desktop Version: 4.9.1

### Steps to reproduce the behavior

  1. Install Docker Desktop for Arch Linux from the official website.
  2. Open Docker Desktop and it will not start.

**Comment by aiordache** [comment]
Hi @NashiraDeer. The diagnostic logs show that `/etc/subuid` and `/etc/subgid` files are missing:
```
opening /etc/subuid: open /etc/subuid: no such file or directory
```

Can you create them and then restart Docker Desktop please?
```
$ echo <USER>:10000:65536 >> /etc/subuid
$ echo <USER>:10000:65536 >> /etc/subgid
```

**Comment by NashiraDeer** [comment]
Thanks, that fixed it and now Docker is starting normally.

**Comment by komildeveloper** [comment]
> Hi @NashiraDeer. The diagnostic logs show that `/etc/subuid` and `/etc/subgid` files are missing:
> 
> ```
> opening /etc/subuid: open /etc/subuid: no such file or directory
> ```
> 
> Can you create them and then restart Docker Desktop please?
> 
> ```
> $ echo <USER>:10000:65536 >> /etc/subuid
> $ echo <USER>:10000:65536 >> /etc/subgid
> ```

hi, I tried the following but it still doesn't work

**Comment by HubKing** [comment]
First, the commands did not work with error messages. I manually created the two files and wrote `<USER>:10000:65536` in them. But Docker Desktop still did not launch. What gives?

**Comment by Mipsters** [comment]
> First, the commands did not work with error messages. I manually created the two files and wrote `<USER>:10000:65536` in them. But Docker Desktop still did not launch. What gives?

you shouldn't write "\<USER\>", but your username, as in the content of $USER
a working copy-paste command will be
as sudoer:
```bash
echo $USER:10000:65536 | sudo tee --append /etc/subuid /etc/subgid
```
as root:
```bash
echo $USER:10000:65536 >> /etc/subuid
echo $USER:10000:65536 >> /etc/subgid
```
at least that did it for me

**Comment by komildeveloper** [comment]
> 

Thank, it's working

**Comment by chaderenyore** [comment]
> 

Hi, I have those files already created before, but it still doesn't work for me.
The docker desktop stays at "Docker Desktop Starting".

**Comment by HubKing** [comment]
Meh. It turned out that DD is a piece of crap (I could not get it working on Linux, but I have used it on Windows). Portainer has a lot better interface and more features.

**Comment by PandaFencing** [comment]
If `/etc/subuid` and `/etc/subgid` are missing, they need to be created.
Both should contain entries in the form -
`<username>:<start of id range>:<id range size>`. For example, to allow the current user
to use IDs from 100000 to 165535:

```console
$ grep "$USER" /etc/subuid >> /dev/null 2&>1 || (echo "$USER:100000:65536" | sudo tee -a /etc/subuid)
$ grep "$USER" /etc/subgid >> /dev/null 2&>1 || (echo "$USER:100000:65536" | sudo tee -a /etc/subgid)
```

To verify the configs have been created correctly, inspect their contents:

```console
$ echo $USER
exampleuser
$ cat /etc/subuid
exampleuser:100000:65536
$ cat /etc/subgid
exampleuser:100000:65536

**Comment by JasurJamolovdev** [comment]
yea, the docker desktop very simple and easy! like from you

**Comment by ananyo141** [comment]
It worked! For anyone scourging the internet for answers, in my case I had downloaded the AUR package, after enabling kvm and everything, docker-desktop just said unable to start docker engine. Created the files and et viola!
