### ISSUE TITLE
"Docker Desktop is starting" forever in Ubuntu 20

### ISSUE THREAD

**Issue by mfrutos** [docker/desktop-linux#33]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 5b8c0c4d-0905-401f-a41d-f6171eeef71f/20220620214536

### Expected behavior
Docker Desktop should start

### Actual behavior
Docker Desktop keeps starting forever

### Information

  - Linux distro: Ubuntu
  - Distro version: Ubuntu 20.04.4 LTS
  - Docker Desktop Version:

### Steps to reproduce the behavior

```
$ service docker status
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-06-20 22:37:57 IST; 14min ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 103605 (dockerd)
      Tasks: 13
     Memory: 32.9M
     CGroup: /system.slice/docker.service
             └─103605 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
```
  2. Start Docker Desktop
  3. It will be there broken forever.

**Comment by aiordache** [comment]
Hi @mfrutos.  Diagnostics logs show an error when setting up ID maps for virtiofsd namespace:
```
retrieving subordinate UID range: no range for <USER> found in /etc/subuid
```
Can you check please that `/etc/subuid` and `/etc/subgid` files contain
```
<USER>:10000:65536 
```
If not, can you add it?
```
$ echo <USER>:10000:65536 >> /etc/subuid
$ echo <USER>:10000:65536 >> /etc/subgid
```

**Comment by Deoo7** [comment]
bash: USER: No such file or directory

what's the problem?

**Comment by krzysiekcr** [comment]
> bash: USER: No such file or directory
> 
> what's the problem?

you have to replace <USER> with your username
