### ISSUE TITLE
Desktop for linux could not create files, while Desktop for Mac can

### ISSUE THREAD

**Issue by UnwishingMoon** [docker/desktop-linux#38]
I created a docker compose file containing this container:
```yml
apache:
    image: php:7.4-apache
    container_name: apache
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/folder
```

Inside the same folder there is a script called `test.php` that puts a string inside a file named `file.txt` (it does create the file if it does not exist):
```php
<?php
$test = "string write";
file_put_contents(__DIR__ ."/file.txt", $test);
?>
```

The container is run as `root` but apache serves and execute php code with the user `www-data (id 33)`
On DD for Mac the file is created and the string is written inside it with the user changed to the container `root` user

`ls -alF` output from inside the container:
```bash
drwx------  27 root root   864 Jun 29 11:17 ./
drwxr-xr-x   4 root root  4096 Jun 29 11:12 ../
-rw-r--r--   1 root root    12 Jun 29 11:18 file.txt
```

`ls -alF` output from the host:
```bash
-rw-r--r--    1 diego  staff     12 29 Giu 11:18 file.txt
```

On DD for Linux the file can't be created with the following error:
```
Warning: file_put_contents(/var/www/html/folder/file.txt): failed to open stream: Permission denied in /var/www/html/folder/test.php on line 8
```

If the file already exists writing to it as `www-data` just works. 

`ls -alF` output from inside the container before writing from script:
```bash
drwxrwxr-x 13 root root  4096 Jun 29 11:38 ./
drwxr-xr-x  4 root root  4096 Jun 29 11:38 ../
-rw-r--r--  1 root root     0 Jun 29 11:42 file.txt
```

After the script execution no error is shown and string is written inside the file (the write bit for everyone is not set):
```bash
drwxrwxr-x 13 root root  4096 Jun 29 11:38 ./
drwxr-xr-x  4 root root  4096 Jun 29 11:38 ../
-rw-r--r--  1 root root    12 Jun 29 11:42 file.txt
```

From host the files are the following (owned by the host user):
```bash
drwxrwxr-x 13 sat sat  4096 giu 29 11:42 ./
drwxrwxr-x  4 sat sat  4096 giu 29 09:37 ../
-rw-r--r--  1 sat sat    12 giu 29 11:42 file.txt
```

- [x] I have tried with the latest version of Docker Desktop
- [x] I have tried disabling enabled experimental features
- [x] I have uploaded Diagnostics
- DD Linux Diagnostics ID: `43af70ed-df47-4b70-aa50-2aeb095b132d/20220629072841`
  - Linux distro: Ubuntu 22.04
  - Docker Desktop Version: 4.9.1
- DD Mac Diagnostics ID (for comparison if needed): `5C164D53-9EDF-4C3A-9A89-7244B29FB3B2/20220629073952`
  - Version: Monterey 12.4
  - Docker Desktop Version: 4.9.1

### Expected behavior

I expected DD for Linux to work exactly like DD for Mac and being able to create the file if it does not exist and remap the user id

**Comment by p1-0tr** [comment]
hi @UnwishingMoon, thanks for reporting your issue, and sorry for the inconvenience. Sounds like this is related to https://github.com/docker/desktop-linux/issues/9 . I'll let you know once a fix is available.

**Comment by UnwishingMoon** [comment]
Perfect, I will follow the other issue and test a solution when available
