### ISSUE TITLE
docker compose commands produce a permission denied error

### ISSUE THREAD

**Issue by nicekiwi** [docker/desktop-linux#4]
- [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: b30021e2-4cf7-43d9-b749-ef9c0998b033/20220410082535

### Expected behavior

Docker compose builds the compose script.

### Actual behavior

![image](https://user-images.githubusercontent.com/738975/162609765-810e17b6-07ff-4646-a4d6-7b9a51906d77.png)

```
error getting credentials - err: exit status 1, out: `error getting credentials - err: fork/exec /usr/bin: permission denied, out: ```
```

### Information

My compose script runs perfectly with standard docker engine, but get the error above when running with docker desktop's compose command.

Docker commands run fine, just compose that seems to have issues.

-->
  - Linux distro: Kubuntu
  - Distro version: 21.10
  - Docker Desktop Version: 

```
Docker Compose version v2.2.3

Client: Docker Engine - Community
 Cloud integration: v1.0.23
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:07 2022
 OS/Arch:           linux/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.8.0 (77103)
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:46:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Steps to reproduce the behavior

1. Install docker desktop
2. reboot
3. try to build a compose script

**Comment by aiordache** [comment]
Hi @nicekiwi ! Thanks for raising the issue.

Can you check please that the property `credentialHelper` from `~/.docker/desktop/settings.json` is set to `docker-credential-pass`? 
```
  "credentialHelper": "docker-credential-pass",
```
This may require you to login again if you pull a private image, as the credentials have not been stored correctly in case this property was different. 

I am investigating something related to the credential helper and it would help if you can confirm this helps in fixing your issue.

**Comment by nicekiwi** [comment]
@aiordache currently it's set to "". I'll change it.

**Comment by nicekiwi** [comment]
@aiordache now that I set the variable and restarted docker desktop, compose is working correctly.

**Comment by nicekiwi** [comment]
Having set `docker-credential-pass` in the josn file, docker desktop will not stay logged in. If I quit the app and start it again I will have to login again.

**Comment by leonardocartaxo** [comment]
It worked for me thanks @aiordache

**Comment by p1-0tr** [comment]
Resolved. Closing.
