### ISSUE TITLE
Docker Desktop starting forever in archlinux

### ISSUE THREAD

**Issue by wilsntn** [docker/desktop-linux#43]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 59014ba0-d58a-4f1d-b3f9-81fe58247896/20220707181044

### Expected behavior
Start
### Actual behavior
Not Start
### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new?
  - Did the problem appear with an update? 
  - 
  - Linux distro: Arch Linux
  - Distro version: Kernel 5.18.7-arch1-1 
  - Docker Desktop Version: 4.10.1

**Comment by aiordache** [comment]
Hi @wilsntn!
The logs show an error related to the ID maps setup for virtiofs:
```
retrieving subordinate UID range: no range for <USER> found in /etc/subuid
```
Can you add a range for your user and restart DD please ?
example:
```
$ echo <USER>:10000:65536 >> /etc/subuid
$ echo <USER>:10000:65536 >> /etc/subgid
```

**Comment by wilsntn** [comment]
Thank you! Solved my problem, i have the same in my desktop may i try the same?

**Comment by aiordache** [comment]
@wilsntn Yes, you can check the log at `/.docker/desktop/log/host/com.docker.driver.amd64-linux.log` for the boot error. If it is the same, you need to setup the UID range.

**Comment by wilsntn** [comment]
Thats worked for me thank you so much!

**Comment by mateomazzucco11** [comment]
@aiordache Hey, I am having the same problem. But I didn't understand the solution, I'm new (I have manjaro). 
when I put echo <USER>:10000:65536 >> /etc/subuid I get this error zsh: no such file or directory: USER

**Comment by p1-0tr** [comment]
@mateomazzucco11 - the solution is to create `/etc/subuid` and `/etc/subgid`. Those are configuration files that allow users to map given ranges of user and group ids in user namespaces. Both can contain multiple entries in the form `<user name>:<start of range>:<range size>` (Docker Desktop will pick up the first entry for the current user). You can find more info about these configs here - https://man7.org/linux/man-pages/man5/subuid.5.html .

**Comment by mateomazzucco11** [comment]
@p1-0tr an okay perfect, I just created it but it is still the same. Sorry for the delay, I did not have time to see it.

**Comment by p1-0tr** [comment]
@mateomazzucco11 - could you submit diagnostics - https://docs.docker.com/desktop/linux/troubleshoot/#diagnose-and-feedback ?

**Comment by mateomazzucco11** [comment]
@p1-0tr I can't enter options because I have infinite spinning left.

**Comment by p1-0tr** [comment]
@mateomazzucco11 - you can gather diagnostics from the CLI - https://docs.docker.com/desktop/linux/troubleshoot/#diagnosing-from-the-terminal .

**Comment by mateomazzucco11** [comment]
@p1-0tr unzip –l /tmp/BE9AFAAF-F68B-41D0-9D12-84760E6B8740/20190905152051.zip

**Comment by p1-0tr** [comment]
@mateomazzucco11 - it looks like accidentally created `/etc/subuid` as a directory

    [2022-07-14T11:42:23.284159927Z][com.docker.driver.amd64-linux][F] setting up ID maps for virtiofsd namespace: retrieving subordinate UID range: reading /etc/subuid: read /etc/subuid: is a directory
    
(the log can be found in `~/.docker/desktop/log/host/com.docker.driver.amd64-linux.log`).

You'll need to remove `/etc/subuid` and I assume `/etc/subgid`, then run the following:

    echo $(whoami):10000:65536 >> /etc/subuid
    echo $(whoami):10000:65536 >> /etc/subgid
    
and make sure that both files exist, and contain an entry in the form `<YOUR USERNAME>:10000:65536`. e.g.

    cat /etc/subuid
    p10tr:10000:65536

Hope this helps :)

**Comment by p1-0tr** [comment]
@mateomazzucco11 - ah, I haven't thought of that, `sudo` will mess with `whoami` anyway. In that case are you able to open the files in an editor?

**Comment by mateomazzucco11** [comment]
@p1-0tr  If I put echo $(whoami):10000:65536 >> /etc/subuid it does not allow me to open it in the editor. But if I put /etc/subiud if but it is created and it would not be what we need it seems to me.

**Comment by p1-0tr** [comment]
@mateomazzucco11 - sorry, what I meant is are you able to open `/etc/subuid` in an editor, e.g.

    sudo vi /etc/subuid
    
or 
   
   sudo nano /etc/subuid
   
and then enter `<USER>:10000:65536` (but replace <USER> with your username), manually. And do the same for `/etc/subgid`.

**Comment by mateomazzucco11** [comment]
@p1-0tr It worked, I had to restart the pc as the last step. You are a genius thanks!

**Comment by VaradBelwalkar** [comment]
**@p1-0tr** Thanks, It worked perfectly !

**Comment by komildeveloper** [comment]
> @mateomazzucco11 - sorry, what I meant is are you able to open `/etc/subuid` in an editor, e.g.
> 
> ```
> sudo vi /etc/subuid
> ```
> 
> or
> 
> ```
> sudo nano /etc/subuid
> ```
> 
> and then enter `<USER>:10000:65536` (but replace `<USER>` with your username), manually. And do the same for `/etc/subgid`.

hi, I tried the following but it still doesn't work

**Comment by m44rx** [comment]
I followed the steps and solved the problem thanks -> @p1-0tr

**Comment by Linha-Rocha** [comment]
> @mateomazzucco11 - sorry, what I meant is are you able to open `/etc/subuid` in an editor, e.g.
> 
> ```
> sudo vi /etc/subuid
> ```
> 
> or
> 
> ```
> sudo nano /etc/subuid
> ```
> 
> and then enter `<USER>:10000:65536` (but replace `<USER>` with your username), manually. And do the same for `/etc/subgid`.

This worked for me on EndeavourOS. Thank you very much!

**Comment by sbwcwso** [comment]
> @mateomazzucco11 - it looks like accidentally created `/etc/subuid` as a directory
> 
> ```
> [2022-07-14T11:42:23.284159927Z][com.docker.driver.amd64-linux][F] setting up ID maps for virtiofsd namespace: retrieving subordinate UID range: reading /etc/subuid: read /etc/subuid: is a directory
> ```
> 
> (the log can be found in `~/.docker/desktop/log/host/com.docker.driver.amd64-linux.log`).
> 
> You'll need to remove `/etc/subuid` and I assume `/etc/subgid`, then run the following:
> 
> ```
> echo $(whoami):10000:65536 >> /etc/subuid
> echo $(whoami):10000:65536 >> /etc/subgid
> ```
> 
> and make sure that both files exist, and contain an entry in the form `<YOUR USERNAME>:10000:65536`. e.g.
> 
> ```
> cat /etc/subuid
> p10tr:10000:65536
> ```
> 
> Hope this helps :)

It worked, Thank you very much!

And you can use the following command to change the file, just for others who need it.

```
sudo sh -c "echo $(whoami):10000:65536 >> /etc/subuid"
sudo sh -c "echo $(whoami):10000:65536 >> /etc/subgid"
```

**Comment by marabesi** [comment]
same as @sbwcwso here, after creating the files it worked perfectly.

The only extra info I can share is that I am using the docker desktop for debian but on a pop-os, and it worked perfectly.

**Comment by sambhavsaxena** [comment]
running `systemctl enable docker.service` makes it work fine!
