### ISSUE TITLE
Can't get past the Docker Desktop Starting... screen on Manjaro

### ISSUE THREAD

**Issue by StephenGunn** [docker/desktop-linux#44]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6dba9ac8-249f-4009-9405-315ae6e00b1c/20220708042118

### Expected behavior
Docker desktop should start after logging in.

### Actual behavior
Docker desktop freezes (or stalls for 45+ minutes) on the "Docker Desktop starting..." screen

### Information

  - Linux distro: Manjaro
  - Distro version: 21.3.2
  - Docker Desktop Version: v4.10.1

I see my username in the top bar and the status bar at the bottom says I have connected to the hub.

I have also manually created the `/etc/subuid` and `/etc/subgid` files and added `<USER>:10000:65536` to each of them.

I have restarted after creating the files and tried again with no luck.

**Comment by aiordache** [comment]
Hi @StephenGunn !
Logs show an error related to the `/etc/subuid` file:
```
retrieving subordinate UID range: encountered malformed /etc/subuid entry on line 0
```
You can always check the log at `~/.docker/desktop/log/host/com.docker.driver.amd64-linux.log`  for VM boot errors such as this.

**Comment by M-Gonzalo** [comment]
I also can't get past the "Docker Desktop Starting" screen. I installed it as per the docs on the official site.
I updated the whole system and restarted too, but it's the same issue.

The self-diagnose tool says this:

<details>
<summary>Details</summary>

> 
> [FAIL] DD0032: do Docker networks overlap with host IPs? Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?
> [SKIP] DD0030: is the image access management authorized?
> [PASS] DD0033: does the host have Internet access?
> 
> Please investigate the following 1 issue:
> 
> 1 : The test: can a VM be started?
>     Failed with: vm has not started: failed to open kmsg.log: open /home/gonza-m/.docker/desktop/log/vm/kmsg.log: no such file or directory
> 
> The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.

</details>

The Diagnostics ID from the GUI is `6d8f9759-416e-48c3-a55f-51691a3fde1a/20220729190054`

**Comment by aiordache** [comment]
@M-Gonzalo Your diagnostics log shows the `/etc/subuid` file is missing.
```
opening /etc/subuid: open /etc/subuid: no such file or directory
```
Can you create those files and restart Docker Desktop? 
As mentioned before, you can check for errors in `~/.docker/desktop/log/host/com.docker.driver.amd64-linux.log` when DD fails to start.

**Comment by M-Gonzalo** [comment]
> @M-Gonzalo Your diagnostics log shows the `/etc/subuid` file is missing.
> 
> ```
> opening /etc/subuid: open /etc/subuid: no such file or directory
> ```
> 
> Can you create those files and restart Docker Desktop? As mentioned before, you can check for errors in `~/.docker/desktop/log/host/com.docker.driver.amd64-linux.log` when DD fails to start.

Thanks. It worked.

For those who come here looking for a solution, this helped me: https://github.com/containers/podman/issues/6572#issuecomment-642877777

**Comment by p1-0tr** [comment]
We've updated our docs with details about the file sharing set up used by DD - https://docs.docker.com/desktop/install/linux-install/#file-sharing .
