### ISSUE TITLE
Docker Desktop 4.10.1 starting forever on Garuda Linux (Arch-based distro)

### ISSUE THREAD

**Issue by ameya-deshmukh** [docker/desktop-linux#47]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3fc4c344-e683-4982-b96b-f420da642730/20220710125223

### Expected behavior
Starting and functioning normally as Docker Desktop is intended to
### Actual behavior
Displays "Docker Desktop starting..." forever 
![Screenshot_4](https://user-images.githubusercontent.com/74180822/178146112-5d8a1a5c-e597-43d6-8208-1e56685645fe.png)

### Information
 - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? First install of Docker Desktop on this system
  - Linux distro: Garuda Linux
  - Distro version: Kernel 5.18.9-zen1-1-zen
  - Docker Desktop Version: 4.10.1

### Steps to reproduce the behavior
  1. Install Garuda Linux with the above version
  2. Install Docker Desktop 4.10.1 for Arch Linux
  3. Try to run it by logging in

**Comment by MahmoudAFarag** [comment]
I solved my issue by creating 2 files ```/etc/subuid``` and ```/etc/subgid``` and adding the following line in each of them:

```<USER>:10000:65536``` 

Replace <USER> with your user name

**Comment by ameya-deshmukh** [comment]
Hi, I did this. The problem persists

**Comment by p1-0tr** [comment]
@ameya-deshmukh thanks submitting your issue and sorry for the inconvenience.

In the diagnostic logs I can see that `/etc/subuid` and `/etc/subgid` are missing:

    [com.docker.driver.amd64-linux][F] setting up ID maps for virtiofsd namespace: retrieving subordinate UID range: opening /etc/subuid: open /etc/subuid: no such file or directory

(in `~/.docker/desktop/log/host/com.docker.driver.amd64-linux.log`). This error will prevent DD from making progress, so if something else is wrong I won't be able to tell from the current set of logs.

One thing worth trying would be to quit DD and make sure that none of its processes linger (especially `com.docker.backend`), and start DD again. If that does not work, could you create a new set of diagnostics?

**Comment by ameya-deshmukh** [comment]
Thanks a lot, it's working now! Closing this issue

> @ameya-deshmukh thanks submitting your issue and sorry for the inconvenience.
> 
> In the diagnostic logs I can see that `/etc/subuid` and `/etc/subgid` are missing:
> 
> ```
> [com.docker.driver.amd64-linux][F] setting up ID maps for virtiofsd namespace: retrieving subordinate UID range: opening /etc/subuid: open /etc/subuid: no such file or directory
> ```
> 
> (in `~/.docker/desktop/log/host/com.docker.driver.amd64-linux.log`). This error will prevent DD from making progress, so if something else is wrong I won't be able to tell from the current set of logs.
> 
> One thing worth trying would be to quit DD and make sure that none of its processes linger (especially `com.docker.backend`), and start DD again. If that does not work, could you create a new set of diagnostics?

**Comment by Parables** [comment]
@ameya-deshmukh  Did you install Docker  client binaries from pacman or from the static binaries https://docs.docker.com/desktop/install/archlinux/#install-docker-desktop

**Comment by vicrg** [comment]
Thanks a lot!! Works like a charm
