### ISSUE TITLE
Not being able to install on Fedora 36

### ISSUE THREAD

**Issue by ayan-iiitd** [docker/desktop-linux#48]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Installs normally

### Actual behavior
```
Error: 
 Problem: conflicting requests
  - nothing provides docker-ce-cli needed by docker-desktop-4.10.1-82475.x86_64

```

### Information

  - Linux distro:
  - Distro version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. Downloaded from https://desktop.docker.com/linux/main/amd64/docker-desktop-4.10.1-x86_64.rpm?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-linux-amd64
  2. Tried `sudo dnf install docker-desktop-4.10.1-x86_64.rpm`
  3. Got error.
  4. Then tried `sudo dnf install docker-compose`
  5. Got error again.

**Comment by p1-0tr** [comment]
@ayan-iiitd - please follow https://docs.docker.com/desktop/linux/install/fedora/#install-docker-desktop

**Comment by ayan-iiitd** [comment]
> @ayan-iiitd - please follow https://docs.docker.com/desktop/linux/install/fedora/#install-docker-desktop

Thanks. I did follow from there only. But one thing I missed was

> To install Docker Desktop on Fedora:
> 
>     Set up [Docker’s package repository](https://docs.docker.com/engine/install/fedora/#set-up-the-repository).

Just a suggestion, this can be moved up to the prerequisites section.
