### ISSUE TITLE
Cannot login on Ubuntu 21.10 with Desktop v4.8.0: Error storing credentials

### ISSUE THREAD

**Issue by aerabi** [docker/desktop-linux#5]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
    + 4.7.0: `1b52fd5f-f1c1-496d-ab6a-f778cd3d1921/20220413101441`
    + 4.8.0: `1b52fd5f-f1c1-496d-ab6a-f778cd3d1921/20220413113454`

### Expected behavior

I should be able to log in after I have done `pass init`.

### Actual behavior

It says:

```
Error saving credentials: error storing credentials - err: exec: "docker-credential-docker-desktop": executable file not found in $PATH, out: ``
```

### Information

  - Linux distro: Ubuntu
  - Distro version: 21.10
  - Docker Desktop Version: 4.7.0 (77074) and 4.8.0 (77103)

I can fix it by removing the following line from `~/.docker/config.json`:
```json
"credsStore": "desktop"
```
Or by changing the value to `pass`.

Note. Following the same instructions, logging in worked on Ubuntu 22.04 (beta) with an older version of Docker Desktop (76787).

**Comment by aiordache** [comment]
Hi @aerabi ! We found a bug with credstoreHelper being reset and we are preparing a new build.

Can you set please the credentialHelper from ~/.docker/desktop/settings.json to docker-credential-pass?
```
  "credentialHelper": "docker-credential-pass",
```
This may require you to login again if you pull a private image, as the credentials have not been stored correctly.
Unfortunately, it is being reset each time you apply new settings from the settings panel. We'll have a fix for this soon.
Thanks!

**Comment by aerabi** [comment]
Thanks, @aiordache. :pray: No worries, I just wanted to inform you of the problem. If you're already fixing it, then I'm happy. :whale:

**Comment by p1-0tr** [comment]
Resolved. Closing.
