### ISSUE TITLE
Windows Mode on Docker Desktop for Linux

### ISSUE THREAD

**Issue by chighfi1** [docker/desktop-linux#50]
Hi,

I am trying to switch from "Linux Mode" to "Windows Mode" while using docker desktop for linux.

In docker for windows, I am able to switch from "Linux Mode" to "Windows Mode" by right clicking the whale icon in the system tray. In Fedora desktop however, if I left click or right click the whale or "Docker" button on the upper left hand side, I do not see the option. (I cannot screenshot from linux machine, it's booted on different HD, this screenshot is from a tutorial video, but my intent is to point out what I'm talking about when I say "Docker" button on top left side of Linux) 

![image](https://user-images.githubusercontent.com/45884468/180356555-4e052a9c-cb1b-4d64-98cf-9b2fc2be7bf7.png)

I also have found out how to switch modes in powershell as well
/DockerCli.exe -SwitchDaemon

But have yet to find an article about doing so from linux terminal.

**Comment by p1-0tr** [comment]
@chighfi1 - thanks for your question. Switching Windows containers is a Windows-specific feature, and so it is not available on Linux or macOS.
