### ISSUE TITLE
Docker Desktop don't start in Arch Linux/Arcolinux

### ISSUE THREAD

**Issue by aginanjar** [docker/desktop-linux#51]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - [x] I have followed from this issue : https://github.com/docker/desktop-linux/issues/32#issuecomment-1161436024
  - Diagnostics ID: 87eb6ec5-ccbe-47ee-9f49-e235dc4e2f4d/20220722170754

### Expected behavior
Docker Desktop runs

### Actual behavior
Stuck with "Docker Desktop Starting..."
 
### Information

This problem happened in Docker Desktop 4.10.1.

- Linux distro: Arch Linux/Arcolinux
- Distro version: Rolling
- Docker Desktop Version: 4.10.1

Previously, I moved docker installation path from `/var/lib/docker` to `/home/user/docker`. `docker` runs as well, but if I open `docker-desktop`, and run `docker ps` its get me this message : `Cannot connect to the Docker daemon at unix:///home/user/.docker/desktop/docker.sock. Is the docker daemon running?
### Steps to reproduce the behavior

1. Install Docker
2. Move from default path, example : `/var/lib/linux` to other path
3. Run `docker run hello-world`
4. Check `docker ps` 
5. Install Docker Desktop for Arch Linux from the official website.
6. Open Docker Desktop, it'll stuck in "Docker Desktop Starting ..."
7. Check `docker ps`

**Comment by aiordache** [comment]
Hi @aginanjar. The logs show an issue with setting up ID maps for virtiofsd:
```
retrieving subordinate UID range: opening /etc/subuid: no such file or directory
```
You need to create 2 files `/etc/subuid` and `/etc/subgid` with ranges for user and group id mapping.
An example:
```
$ echo <USER>:10000:65536 >> /etc/subuid
$ echo <USER>:10000:65536 >> /etc/subgid
```

**Comment by OyewoleOyedeji** [comment]
@aginanjar thanks the solution suggested works!

**Comment by ahmad-gospurr** [comment]
@aiordache works like a charm. Thanks!

**Comment by thunderjet12** [comment]
> Hi @aginanjar. The logs show an issue with setting up ID maps for virtiofsd:
> 
> ```
> retrieving subordinate UID range: opening /etc/subuid: no such file or directory
> ```
> 
> You need to create 2 files `/etc/subuid` and `/etc/subgid` with ranges for user and group id mapping. An example:
> 
> ```
> $ echo <USER>:10000:65536 >> /etc/subuid
> $ echo <USER>:10000:65536 >> /etc/subgid
> ```
Thanks alot Bro it realy saved me alot of time after day of strugle 
i 'm Using Endavour OS Artimes  and want to install docksal  ["wordpress, drupal, laravel,...etc" Dev Enviroment 'docker based' ]

**Comment by p1-0tr** [comment]
We've updated our documentation with more details on the file sharing set up used by DD - https://docs.docker.com/desktop/install/linux-install/#file-sharing . And included subordinate ID delegation configuration in the list of installation pre-requisites.

**Comment by runckode** [comment]
I fallowed docker-documentation and : ╭─    ~/Downloads ▓▒░────────────────────────────────────────────────────────────░▒▓ 2 ✘  at 06:03:53   ─╮
╰─
─╯
sudo setfacl -Rm u:$USER:rwX ~/Documents/development
sudo setfacl -Rm d:u:$USER:rwX ~/Documents/development

setfacl: Option -m: Invalid argument near character 3
setfacl: Option -m: Invalid argument near character 5
╭─    ~/Downloads ▓▒░────────────────────────────────────────────────────────────░▒▓ 2 ✘  at 06:04:26   ─╮
╰─
─╯
sudo setfacl -Rm u:"$USER":rwX ~/Documents/development
sudo setfacl -Rm d:u:"$USER":rwX ~/Documents/development

╭─    ~/Downloads ▓▒░──────────────────────────────────────────────────────────────░▒▓ ✔  at 06:04:57   ─╮
╰─
─╯
grep "$USER" /etc/subuid >> /dev/null 2&>1 || (echo "$USER:100000:65536" | sudo tee -a /etc/subuid)
grep "$USER" /etc/subgid >> /dev/null 2&>1 || (echo "$USER:100000:65536" | sudo tee -a /etc/subgid)
╭─    ~/Downloads ▓▒░──────────────────────────────────────────────────────────────░▒▓ ✔  at 06:06:31   ─╮
╰─
─╯
sudo grep "$USER" /etc/subuid >> /dev/null 2&>1 || (echo "$USER:100000:65536" | sudo tee -a /etc/subuid)
sudo grep "$USER" /etc/subgid >> /dev/null 2&>1 || (echo "$USER:100000:65536" | sudo tee -a /etc/subgid)
╭─    ~/Downloads ▓▒░──────────────────────────────────────────────────────────────░▒▓ ✔  at 06:12:21   ─╮
╰─
─╯
cat /etc/subuid

irrefl:100000:65536
╭─    ~/Downloads ▓▒░──────────────────────────────────────────────────────────────░▒▓ ✔  at 06:12:29   ─╮
╰─
─╯
cat /etc/subgid
irrefl:100000:65536
