### ISSUE TITLE
docker throws exception on Raspbian bullseye

### ISSUE THREAD

**Issue by the100rabh** [docker/desktop-linux#56]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
`docker ps ` should not throw error

### Actual behavior

running docker ps gives the following output

```
fatal error: index out of range
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x1b95c1b, 0x12})
	/usr/local/go/src/runtime/panic.go:1198 +0x60 fp=0x7e8f3434 sp=0x7e8f3420 pc=0x7e6e48
runtime.panicCheck1(0x808864, {0x1b95c1b, 0x12})
	/usr/local/go/src/runtime/panic.go:36 +0xb4 fp=0x7e8f3448 sp=0x7e8f3434 pc=0x7e3440
runtime.goPanicIndexU(0x822facc, 0x3f6d08)
	/usr/local/go/src/runtime/panic.go:93 +0x30 fp=0x7e8f346c sp=0x7e8f3448 pc=0x7e35a4
runtime.moduledataverify1(0x2c94340)
	/usr/local/go/src/runtime/symtab.go:586 +0x514 fp=0x7e8f34cc sp=0x7e8f346c pc=0x808864
runtime.moduledataverify(...)
	/usr/local/go/src/runtime/symtab.go:562
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:687 +0x3c fp=0x7e8f34f8 sp=0x7e8f34cc pc=0x7eb3e8
runtime.rt0_go()
	/usr/local/go/src/runtime/asm_arm.s:168 +0x84 fp=0x7e8f3538 sp=0x7e8f34f8 pc=0x81b158
```

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Not sure 
  - Linux distro: Raspbian 
  - Distro version: bullseye 
  - Docker Desktop Version: 5:20.10.17~3-0~raspbian-bullseye

Not able to update or reinstall docker on that system as well.

**Comment by aiordache** [comment]
@thaJeztah is this a docker/cli or moby/moby issue?

**Comment by the100rabh** [comment]
Sorry to bother you folks here, the issue with the incorrect repo which was installing docker for me.
