### ISSUE TITLE
Docker desktop does not start

### ISSUE THREAD

**Issue by amirrh6** [docker/desktop-linux#58]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features [See note 1]
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 94570555-f08d-4fed-9693-bdf35ab0401a/20220811085331

### Expected behavior
Docker desktop should be displayed if started from Applications Menu or command line.

### Actual behavior
Docker desktop GUI is not shown at all, neither the tray icon.

### Information

  - Linux distro: Mint
  - Distro version: 20.3 (Based on Ubuntu 20.04)
  - Docker Desktop Version: docker-desktop-4.11.0-amd64.deb [See note 2]

### Steps to reproduce the behavior

Docker GUI was displayed once with the Terms Agreement dialog, Once I accepted the terms, it closed and subsequent attempts did not start it.

  1. Run Docker desktop from Applications Menu or via `systemctl --user start docker-desktop`

---
### Note 1
I was unable to access Docker GUI to disable / enable experimental features.

### Note 2
I was unable to obtain a version via command line.
All the following commands output 'unexpected end of JSON input':
- `docker compose version`
- `docker --version`
- `docker version`

**Comment by aiordache** [comment]
@amirrh6 Can you try removing your `~/.docker` directory  and then restart Docker Desktop please? Make sure you back it up first if you have important files in there.

Which version of docker CLI are you using? Can you provide the output of
```
apt list --installed | grep docker
```
We are trying to understand why the config/context files are getting corrupted.

**Comment by aiordache** [comment]
@amirrh6 The default disk size for the VM is 64GB, you may not have enough disk space left.

You can manually set the value for `diskSizeMiB` in `~/.docker/desktop/settings.json` to the size you want to allocate. Remove `~/.docker/desktop/vms/0/data/Docker.raw` and try starting Docker Desktop again.

**Comment by amirrh6** [comment]
Thank you, @aiordache
It works like a charm.
