### ISSUE TITLE
Login URI handler mimetype/action not registered automatically in Kubuntu

### ISSUE THREAD

**Issue by nicekiwi** [docker/desktop-linux#6]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: b30021e2-4cf7-43d9-b749-ef9c0998b033/20220414030808

### Expected behavior
When clicking the browser link to open Docker Desktop after authenticating, Docker Desktop should open and log in.

### Actual behavior
Either nothing happens and Docker Desktop does not log in, or a system error dialog is displayed saying there is not handler for "docker-desktop:://auth-url-here". 

The only way to login is to look for the `docker-desktop-uri-handler.desktop` file in `/usr/share/applications` and call the executable directly and pasting in the `docker-desktop://..` url console logged from the browser screen. Then docker desktop app will open and log in correctly.

### Information

  - Linux distro: Kubuntu
  - Distro version: 21.10
  - Docker Desktop Version: 4.8.0 (77103)
  - Browser: Google Chrome

### Steps to reproduce the behavior

1. Install Kubuntu 21.10
2. Install Docker Desktop .deb
3. Click login in Docker Desktop
4. Complete auth in browser
5. Click popup link from browser to re-open Docker Desktop to complete login

This appears to be the case for KDE in general, not just Kubuntu, I've experienced the same on KDE Neon and similar issues in KDE Neon for Slack login via the browser.

**Comment by aiordache** [comment]
@nicekiwi  Thank you very much for the details! We'll have a look at this and let you know once we get a new build with a fix.

**Comment by nicekiwi** [comment]
![image](https://user-images.githubusercontent.com/738975/164421336-37d0c974-8fe5-41e7-9e80-0666693bb8bb.png)

**Comment by p1-0tr** [comment]
@nicekiwi with a fresh install of kubuntu 21.10 I wasn't able to get a repro of this issue, I wonder if it could be down to having different versions of `kio`, in my case:

    $ apt list --installed | grep kio

    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

    kio-audiocd/impish,now 4:21.08.1-0ubuntu1 amd64 [installed,automatic]
    kio-extras-data/impish,impish,now 4:21.08.1-0ubuntu1 all [installed,automatic]
    kio-extras/impish,now 4:21.08.1-0ubuntu1 amd64 [installed,automatic]
    kio/impish,now 5.86.0a-0ubuntu3 amd64 [installed,automatic]
    libkf5kiocore5/impish,now 5.86.0a-0ubuntu3 amd64 [installed,automatic]
    libkf5kiofilewidgets5/impish,now 5.86.0a-0ubuntu3 amd64 [installed,automatic]
    libkf5kiogui5/impish,now 5.86.0a-0ubuntu3 amd64 [installed,automatic]
    libkf5kiontlm5/impish,now 5.86.0a-0ubuntu3 amd64 [installed,automatic]
    libkf5kiowidgets5/impish,now 5.86.0a-0ubuntu3 amd64 [installed,automatic]
    qml-module-org-kde-kio/impish,now 5.86.0-0ubuntu1 amd64 [installed,automatic]
    
Also regarding the browser - are you using the proprietary `*.deb` (https://www.google.com/chrome/), or some variant of chromium? I tried with firefox distributed in distro and the proprietary chrome release (version 100.0.4896.127).

**Comment by nicekiwi** [comment]
@p1-0tr Goolge Chrome from the `.deb` 

```
apt list --installed | grep kio

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

kio-audiocd/impish,now 4:21.12.3-0ubuntu1~ubuntu21.10~ppa1 amd64 [installed,automatic]
kio-extras-data/impish,impish,now 4:21.12.3-0ubuntu1~ubuntu21.10~ppa1 all [installed,automatic]
kio-extras/impish,now 4:21.12.3-0ubuntu1~ubuntu21.10~ppa1 amd64 [installed,automatic]
kio/impish,now 5.92.0-0ubuntu1~ubuntu21.10~ppa1 amd64 [installed,automatic]
libkf5kiocore5/impish,now 5.92.0-0ubuntu1~ubuntu21.10~ppa1 amd64 [installed,automatic]
libkf5kiofilewidgets5/impish,now 5.92.0-0ubuntu1~ubuntu21.10~ppa1 amd64 [installed,automatic]
libkf5kiogui5/impish,now 5.92.0-0ubuntu1~ubuntu21.10~ppa1 amd64 [installed,automatic]
libkf5kiontlm5/impish,now 5.92.0-0ubuntu1~ubuntu21.10~ppa1 amd64 [installed,automatic]
libkf5kiowidgets5/impish,now 5.92.0-0ubuntu1~ubuntu21.10~ppa1 amd64 [installed,automatic]
qml-module-org-kde-kio/impish,now 5.92.0-0ubuntu1~ubuntu21.10~ppa1 amd64 [installed,automatic]
```

Using latest packages from official backports ppa. https://kubuntu.org/news/plasma-5-24-3-available-on-kubuntu-21-10/

Is the login handler registered for you here? 

![image](https://user-images.githubusercontent.com/738975/164460805-931b59d7-0128-46fb-bb4b-9de3e398d6b9.png)

**Comment by nicekiwi** [comment]
I was able to make it work as expected by manually adding this File association. 
![image](https://user-images.githubusercontent.com/738975/164462550-e3bc0644-6b99-4ef1-bbf6-108bfa95e673.png)

**Comment by rclilly** [comment]
I'm having a similar issue on Kubuntu 22.04. @nicekiwi's File Associations workaround shown above doesn't work for me as there is no `x-scheme-handler` group in the File Associations settings
![Screenshot_20220510_111142](https://user-images.githubusercontent.com/300181/167694846-c017d88b-dbc1-4f56-a87d-3c70aa319c17.png)
.

**Comment by nicekiwi** [comment]
@rclilly AFAIK the `x-scheme-handler` is just a group, you should be able to create it or add the definition to any of the other groups, I don't think it matters which one.

Though to compound the issue, I'm getting the same problem on Ubuntu 22.04 😬

**Comment by rclilly** [comment]
@nicekiwi Thanks! Even after adding that I still can't get signed into Docker Hub with the desktop app. I can't sign into Tailscale for that extension either.

I don't know if this is related but selecting "Start Docker when you log in" has no effect either. I had to manually add it to Autostart in the System Settings.

**Comment by rclilly** [comment]
I just updated to docker-desktop-4.8.2-amd64.deb and I still can't sign in.

**Comment by p1-0tr** [comment]
@rclilly, sorry for the delay in replying. I've not been able to reproduce the issue, so far. I am running a fresh install of kubuntu, so if it's some misconfiguration which could get propagated through OS upgrades I would not have a chance of running into it (though that's a bit of a wild stab in the dark).

Another plausible explanation could be that the user you run as does not have rights to execute `/opt/docker-desktop/complete-login.sh`, which could cause `/usr/share/docker-desktop-uri-handler.desktop` not to get registered.

Also could you confirm at which point signing in fails for you? I am working under the assumption that you are able to sign-in in the browser, after clicking `sign-in` in the app, and when you get presented with a page with a `Proceed to Docker Desktop` button you are unable to proceed (in my case, I am using firefox, clicking it brings up a pop up, where I can do - `Choose application` -> pick `System Handler` -> `Open Link`).

**Comment by p1-0tr** [comment]
This has been inactive for a while. Feel free to reopen or file a new issue if the problem persists.
