### ISSUE TITLE
Docker Desktop is stuck at starting after upgraded arch package

### ISSUE THREAD

**Issue by elek** [docker/desktop-linux#63]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 76ca0271-e22e-4efc-974e-482d064002d0/20220815071514

### Expected behavior

Docker desktop is started after `systemctl --user restart docker-desktop`

### Actual behavior

UI is loaded, but it shows: "Docker Desktop starting..." and stuck in that phase.

### Information

Using archlinux.

**Worked with 4.8.1.**

Doesn't work with 4.10.1 or with 4.11.1...

Downgrading back to 4.8.1 --> It can be started again...

### Steps to reproduce the behavior

```
rm -rf ~/.docker/desktop
cd /tmp
wget 'https://desktop.docker.com/linux/main/amd64/docker-desktop-4.11.1-x86_64.pkg.tar.zst'
sudo pacman -U /tmp/docker-desktop-4.11.1-x86_64.pkg.tar.zst
systemctl --user restart docker-desktop
```

**Comment by aiordache** [comment]
Hi @elek.
The logs in the diagnostics bundle show the error:
```
setting up ID maps for virtiofsd namespace: retrieving subordinate UID range: no range for <USER> found in /etc/subuid
```
Please follow the documentation on how to setup the ID mapping correctly and give it another try: https://docs.docker.com/desktop/install/linux-install/#file-sharing

**Comment by elek** [comment]
Wow, I was not aware of the [updated](https://github.com/docker/docker.github.io/commit/cd1dec6a1820c84f9740639fdfb3520e79a932e5) documentation. But I checked it now, and worked well.

Thanks for the help.
