### ISSUE TITLE
Arch Linux - Docker Desktop crashes and dumps core when launched via systemd

### ISSUE THREAD

**Issue by martyn0ff** [docker/desktop-linux#73]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7c241760-c90f-49cb-b82a-bbe57c92cdb3/20220913105639

### Expected behavior
Docker Desktop launches with `systemctl --user start docker-desktop`

### Actual behavior
Docker Desktop crashes and dumps core, but keeps running until instructed to stop with `systemctl --user stop docker-desktop`
```
 Sep 13 14:45:58 silentreign systemd-coredump[2303054]: [🡕] Process 2302867 (Docker Desktop) of user 1000 dumped core.
<very long stack trace>
````

### Information

  - Linux distro: Arch Linux x64
  - Distro version: `Linux silentreign 5.19.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Sep 2022 18:09:09 +0000 x86_64 GNU/Linux`
  - Docker Desktop Version: 4.12

### Steps to reproduce the behavior

  1. Install prerequisites as mentioned in https://docs.docker.com/desktop/install/archlinux/
  2. Download and install latest Docker Desktop package for Arch Linux: https://desktop.docker.com/linux/main/amd64/docker-desktop-4.12.0-x86_64.pkg.tar.zst
  3. Run with `systemctl --user start docker-desktop`
  4. Docker Desktop doesn't launch and silently produces core dump, which can be observed from `journalctl --user -xeu docker-desktop`.
  5. With `/opt/docker-desktop/bin/com.docker.backend --with-frontend 2>&1` Docker Desktop starts correctly and seems to be working fine.
  
Same behavior was experienced with Docker Desktop 4.11. Please let me know if any further information is required.

**Comment by aiordache** [comment]
Hi @martyn0ff. 
The process that crashes is the UI and this may be caused by not being able to access the display.
Just to quickly check that this is the issue, you could add `Environment=DISPLAY=:0` (add your display number if different from 0) to the service file as below:
```
$ cat /usr/lib/systemd/user/docker-desktop.service
...
[Service]
ExecStart=/opt/docker-desktop/bin/com.docker.backend
Environment=DISPLAY=:0
....
```
Reload configuration:
```
systemctl --user daemon-reload
```
And try to start Docker Desktop again using systemd:
```
systemctl --user start docker-desktop
```
If this runs fine, then probably you need to ensure that when systemd launches Docker Desktop it has a graphical session running.

**Comment by martyn0ff** [comment]
Thank you @aiordache, you pointed me to the right direction. The issue was that I wasn't using any display manager and start my X session with a bare `startx` which didn't pass `DISPLAY` variable to systemd. I've installed `lightdm` and it passes `DISPLAY` variable to systemd correctly. Closing this issue.
