### ISSUE TITLE
'docker images' vs 'sudo docker images'

### ISSUE THREAD

**Issue by tasyiann** [docker/desktop-linux#79]
## Weird behavior after running Docker Desktop

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 055ed4ef-f03f-49f9-8411-d9c053e37903/20220920125323

### Expected behavior
It is expected the following commands to output the same result.

- `docker images`
- `sudo docker images`

### Actual behavior
However, the above commands don't output the same list of images.

- `docker images`: outputs the images that are also visible in the Docker Desktop GUI.
- `sudo docker images`: outputs images that are not visible in the Docker Desktop GUI.

But, `sudo which docker` and `which docker` output the same path.
Also, `whereis sudo docker` and `whereis docker` output the same paths.

### Information
  - Linux distro: Ubuntu
  - Distro version: 20.04.4 LTS
  - Docker Desktop Version: v4.12.0

### Steps to reproduce the behavior
  1. Start fresh - restart OS.
  2. Run `sudo docker images` and `docker images` WITHOUT running the Docker Desktop yet. The commands will output the same result. The issue is not produced yet.
  3. Now, run Docker Desktop.
  4. Run `sudo docker images` and `docker images`.
  5. You'll get a different list of images.

**Comment by aiordache** [comment]
@tasyiann  Docker Desktop and Docker Engine are separate entities and  using different docker contexts.
The `default` docker context always targets the local docker engine ( `default` is an in-memory context). Docker desktop uses a context named `desktop-linux`.
A context is user-specific  (saved in the user's `~/.docker/contexts` directory), each user can define a different context to use.
On startup, Docker Desktop creates and switches automatically  to the `desktop-linux` context for the user that launched it.

When you run `docker images` as the non-root user (user that launched Docker Desktop), the docker cli targets Docker Desktop. 
When running `sudo docker images`, the docker cli is using the context of the root user which is the default context pointing to the local engine.

**Comment by p1-0tr** [comment]
Hi @ammaryasirnaich, unfortunately accessing GPUs (or other devices) from Docker Desktop for Linux isn't currently supported.

**Comment by ammaryasirnaich** [comment]
> Hi @ammaryasirnaich, unfortunately accessing GPUs (or other devices) from Docker Desktop for Linux isn't currently supported.

@p1-0tr thanks for the reply. Just curious, is this feature in the pipeline for a future release?

**Comment by p1-0tr** [comment]
@ammaryasirnaich currently it is not in the pipeline. If it is a feature you'd like to see in Desktop, feel free to add an item to our public roadmap - https://github.com/docker/roadmap :)

**Comment by johndpope** [comment]
how can I move an image showing up in normal to show up in sudo land? i'm on ubuntu 22.

**Comment by aiordache** [comment]
@johndpope  To transfer an image from the Docker Desktop image cache to the local Docker Engine cache you can try docker save/load:
```
$ docker -c default images
REPOSITORY   TAG       IMAGE ID       CREATED      SIZE

$ docker -c desktop-linux images
REPOSITORY   TAG       IMAGE ID       CREATED      SIZE
busybox      latest    66ba00ad3de8   6 days ago   4.87MB

$ docker -c desktop-linux save busybox | docker -c default load
b64792c17e4a: Loading layer  5.096MB/5.096MB
Loaded image: busybox:latest

$ docker -c default images
REPOSITORY   TAG       IMAGE ID       CREATED      SIZE
busybox      latest    66ba00ad3de8   6 days ago   4.87MB

```

**Comment by johndpope** [comment]
nice thanks
