### ISSUE TITLE
Error every reset error listing credentials no usernames for https://index.docker.io/v1//access-token

### ISSUE THREAD

**Issue by Mipsters** [docker/desktop-linux#85]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7af84bfc-a240-46f6-ab8f-6a5c548271b5/20221007131804

### Expected behavior
docker.io login credentials will be save after shutting down and starting Docker Desktop

### Actual behavior
The following error is displayed
```
error listing credentials - err: exit status 1, out: `no usernames for https://index.docker.io/v1//access-token`
```

### Information

  - Linux distro: manjaro
  - Distro version: 22.0.0 Sikaris
  - Docker Desktop Version: 4.12.0

the command `docker login` does work
so that probably means that I set `pass` correctly
I checked that the gpg mail is the same as my docker account as solved issue #25 

### Steps to reproduce the behavior

  1. press the "login" button in Docker Desktop
  2. login via browser
  3. Docker tray Icon > Quit Docker Desktop
  4. launch Docker Desktop
  5. Error pops up

**Comment by Mipsters** [comment]
> can you try to reset your credstore by running `pass rm -rf docker-credential-helpers` and then try again the sign in?

after I ran this command, docker desktop stopped working for me
when I launched it it would immediately close

I uninstalled it and reinstalled it
deleted ~/.docker/desktop
then it launched

I logged in and restarted docker desktop, and now I remained logged it, so everything works

**Comment by Mipsters** [comment]
this issue keep on happening to me
I've ran `pass rm -rf docker-credential-helpers`
I've deleted `~/.password-store` to hard reset any `pass` configuration
deleted `~/.docker/desktop`

updated to docker desktop 4.14.1

followed the [instructions in the docker documentation](https://docs.docker.com/desktop/get-started/#credentials-management-for-linux-users)
logged in via the "Sign in" button
Quit docker desktop
and upon relaunch, i receive the error message
```
error listing credentials - err: exit status 1, out: `no usernames for https://index.docker.io/v1/`
```

**Comment by aiordache** [comment]
Hi @Mipsters. Sorry for this.  
Can you try [this build](https://desktop-stage.docker.com/linux/main/amd64/93003/docker-desktop-4.16.0-x86_64.pkg.tar.zst) please? It has some improvements in how credentials are handled but I am not sure if it fixes your issue. As you can reproduce it easily, maybe you can confirm if it fixes or not.
Before trying the new build, ensure your password store is reset. Thank you!

**Comment by Mipsters** [comment]
@aiordache I figured it out, and its a bit embarrassing on my part
I followed the [official docker credential management instructions](https://docs.docker.com/desktop/get-started/#credentials-management-for-linux-users) to the letter
actually too much so...

I didn't understand that when I run `pass init`, the `gpg-id` it receives as an argument is the public key generated by `gpg --generate-key` from the previous command
I used the public key given in the example...
like, I literally ran
```
pass init 7865BA9185AFA2C26C5B505669FC4F36530097C2
```

I admit that this is a bad on my part, mostly caused by my unfamiliarity with the `pass` and `gpg` tools
but I think the documentation should be clear to people without that knowledge

the fact that an example public key is written in a copyable window is very misleading
I think that it is fine to make commands that needs to be filled in copyable, but not with an example
I would've expected something along the lines of
```
molly@ubuntu:~$ pass init <generated gpg-id>
mkdir: created directory '/home/molly/.password-store/'
Password store initialized for <generated gpg-id>
```
that way, if I do the same mistake, I'll see
```
mipster@manjaro:~$ pass init <generated gpg-id>
bash: syntax error near unexpected token `newline'
```
which is not very clear, but at least it doesn't work

the issue is resolved because there is no issue
I did open a [PR to the documentation project](https://github.com/docker/docs/pull/16276) to prevent this from happening to anybody else in the future...

**Comment by aiordache** [comment]
No worries @Mipsters! :smile: Thank you for updating the docs if that part is not clear enough.
