### ISSUE TITLE
Not able to install Docker desktop on Linux mint 21

### ISSUE THREAD

**Issue by mark-reijerkerk** [docker/desktop-linux#88]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
A normal Installing from Docker on Linux Mint
### Actual behavior
When installing docker desktop on Ubuntu Mint the installation terminates with the following message
_{
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu vanessa Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
}_
The cause of this is that the "lsb_release" command which is used in the installation script returns "vanessa" where it should return "jammy", the result is that you are unable to install via the script.
When you manually replace vanessa by jammy the installation is going well
### Information

  - Linux distro: Linux mint
  - Distro version: 21
  - Docker Desktop Version: latest

### Steps to reproduce the behavior

  1. See behavior

**Comment by GiorgioDalla** [comment]
Did you manage installation ?

**Comment by hiagofranco** [comment]
Changing 

```
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
 ```
 
to 

```
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
 ```
 
 (step 3 from https://docs.docker.com/engine/install/ubuntu/), solves the problem.

**Comment by mark-reijerkerk** [comment]
After the modification I made, I could successful install Docker on Linux Mint (21, Vanessa)
