### ISSUE TITLE
Transferring Context 20x Slower When Building Images

### ISSUE THREAD

**Issue by siebica** [docker/desktop-linux#92]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
4197210c-be66-4fd7-8ab3-732682bee1ba/20221108134729
### Expected behavior
Building a docker image that requires a large build context is very slow. This happens when transferring the build context (e.g. for 2.9 GB file transfer it takes around 600 seconds so around 5 MB/sec).

### Actual behavior
Building the same image in Windows w/ WSL 2 on a less powerful machine takes 25 seconds - i.e. 22x times faster - for transferring the same 2.9 GB build context.

### Information

  - Linux distro: Arch Linux
  - Distro version: 6.0.7-arch1-1
  - Docker Desktop Version:  4.13.1 (90346) 

I can see some qemu images being started, similar to this one: 
```
qemu-system-x86_64 -accel kvm -cpu host -machine q35 -m 20480 -smp 20 -kernel /opt/docker-desktop/linuxkit/kernel -append page_poison=1 vsyscall=emulate panic=1 nospec_store_bypass_disable noibrs noibpb no_stf_barrier mitigations=off linuxkit.unified_cgroup_hierarchy=1    vpnkit.connect=tcp+bootstrap+client://192.168.65.2:37129/d71ea29418a86a58bd0fb7c590d7897b47b420b5a358d7465126270bd9b43254 vpnkit.disable=osxfs-data console=ttyS0 -initrd /opt/docker-desktop/linuxkit/initrd.img -serial pipe:/tmp/qemu-console2588242146/fifo -drive if=none,file=/home/$USER/.docker/desktop/vms/0/data/Docker.raw,format=raw,id=hd0 -device virtio-blk-pci,drive=hd0,serial=dummyserial -netdev socket,id=net1,fd=3 -device virtio-net-pci,netdev=net1,mac=02:50:00:00:00:01 -vga none -nographic -monitor none -object memory-backend-memfd,id=mem,size=20480M,share=on -numa node,memdev=mem -chardev socket,id=char0,path=virtiofs.sock0 -device vhost-user-fs-pci,queue-size=1024,chardev=char0,tag=virtiofs0
```

Not sure if it could be relatd to any of the configuration below:
- setting **msize** to avoid file I/O degradation: https://wiki.qemu.org/Documentation/9psetup#Performance_Considerations_.28msize.29 
- setting **cache=none** for raw images: https://www.linux-kvm.org/page/Tuning_KVM

### Steps to reproduce the behavior
1. Build a docker image that requires copying a large file inside (e.g. Oracle 19c se2 docker image).

**Comment by aiordache** [comment]
Hi @siebica.
Can you try setting the `useVpnkit` property  in `~/.docker/desktop/settings.json` to false, then quit Docker Desktop and start it again. Is the build still slow?

**Comment by siebica** [comment]
Hi @aiordache,

This fixed it: 14 seconds. Thanks! Was going crazy... :+1: 

![Screenshot_20221108_182919](https://user-images.githubusercontent.com/5282265/200634579-4bc97041-2ebc-4c20-9029-7cb1947ade19.png)

**Comment by hg6185** [comment]
This issue occurs to me, using Docker Desktop on a Mac M1.
However, changing the useVpnkit property is already set to true, changing it to false results in the docker engine not booting. Could the problem lie somewhere else?
