### ISSUE TITLE
kubectl is not available after enabling kubernetes in docker-desktop

### ISSUE THREAD

**Issue by markjfletcher** [docker/desktop-linux#93]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When enabling kubernetes in docker-desktop for linux, I expect the kubectl command to be available.
This behavior is present when working with docker-desktop on Windows and MacOS
### Actual behavior
Enabling kubernetes in docker-desktop for linux and then opening a shell and trying to run kubectl results in a "kubectl: command not found" error
### Information

  - Linux distro: Ubuntu 22.04.1 LTS and Pop OS 22.04
  - Distro version: Ubuntu 22.04.1, Pop OS 22.04
  - Docker Desktop Version: 4.13.1

### Steps to reproduce the behavior

  1. Perform a fresh install of Ubuntu 22.04.1.
  2. Run apt-get update && apt-get upgrade -y to grab all updates.
  3. However, do not update to 22.10 - stick with LTS for now.
  4. Follow the instructions from the docker website as outlined here: https://docs.docker.com/desktop/install/ubuntu/
  5. Once docker desktop is installed, sign in to docker hub and enable kubernetes
  6. Once the kubernetes feature is installed, open a shell prompt and type kubectl

**Comment by p1-0tr** [comment]
hi, thanks for reporting the issue and sorry for the inconvenience. On Linux we opted not to automatically install `kubectl` to avoid clashing with manual/package manager installations of it. That said, point taken, the UX around this can be improved to at least provide an option for DD4L to handle installation of `kubectl`.

For now you can follow instructions here - https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/ - to install `kubectl`.

**Comment by markjfletcher** [comment]
Hi thanks for the clarification - I'll go ahead and close because installing kubectl directly is an acceptable workaround

**Comment by Vimajoshi** [comment]
> hi, thanks for reporting the issue and sorry for the inconvenience. On Linux we opted not to automatically install `kubectl` to avoid clashing with manual/package manager installations of it. That said, point taken, the UX around this can be improved to at least provide an option for DD4L to handle installation of `kubectl`.
> 
> For now you can follow instructions here - https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/ - to install `kubectl`.

This worked for me Thanks
