### ISSUE TITLE
Not automatically logged in sometimes (across reboots), perhaps 2FA-related

### ISSUE THREAD

**Issue by jivanpal** [docker/desktop-linux#96]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0569b7ba-830a-47a5-b72e-42c1a37daf18/20221123104134

### Expected behavior

Docker Desktop should remain logged in, using the credentials stored in `~/.password-store/docker-credential-helpers` as necessary.

### Actual behavior

Docker Desktop becomes logged out sometimes across reboots, unpredictably. Similar to <https://github.com/docker/for-mac/issues/6362>.

### Information

  - Linux distro: Pop!_OS
  - Distro version: 22.04
  - Docker Desktop Version: 4.14.1 (91661)

### Steps to reproduce the behavior

  1. Ensure PGP key is in GPG keyring (via Seahorse / GNOME Passwords and Keys app, or via `gpg -K`).
  2. Ensure GNOME login keyring is unlocked automatically on login (via Seahorse).
  3. Ensure GNOME login keyring contains the password for your PGP key (via Seahorse).
  4. Log in to Docker Desktop for Linux for the first time, using your PGP key to encrypt the locally stored Docker credentials. (If step (3) was not done manually already, you will be asked for the PGP key passphrase, and can choose to store it in the keyring at this point via a checkbox.)
  5. Log out of and log back in to the local user account. See that the login keyring has been unlocked and Docker Desktop is logged in.
  6. Reboot an log in to the local user account. See that the keyring is unlocked, but Docker Desktop may *not* be logged in, despite having access to the credentials. Clicking "Log in" in Docker Desktop takes you immediately to the 2FA code page; it doesn't ask for the username/email and password.

**Comment by SalahAdDin** [comment]
It is even worst for me: it is logged but when I open it, it gives an error.
![image](https://user-images.githubusercontent.com/5034215/204105726-feb9b9be-1ce7-477e-bd1f-dd36b532395c.png)
After clicking `Try Again` it logs in without any problem, but I logged in a long time before.
![image](https://user-images.githubusercontent.com/5034215/204105787-9197b49c-c896-491b-9ac4-164d7d3880aa.png)

This should not happen!

**Comment by aiordache** [comment]
When you get this error, can you check please the status of the gpg-agent service, if there is any error reported there?
```
systemctl --user status gpg-agent
```

**Comment by SalahAdDin** [comment]
@jivanpal Any news here?

**Comment by jivanpal** [comment]
@SalahAdDin Nope, sorry, as I've been continuing to use my MacBook for the time being. However, just yesterday, that one's Docker installation updated to a version that's incompatible with my version of macOS, so I'm being forced to move over to my Thinkpad. I should get some time to test this on the weekend whilst I'm setting that up.

**Comment by SalahAdDin** [comment]
> @SalahAdDin Nope, sorry, as I've been continuing to use my MacBook for the time being. However, just yesterday, that one's Docker installation updated to a version that's incompatible with my version of macOS, so I'm being forced to move over to my Thinkpad. I should get some time to test this on the weekend whilst I'm setting that up.

Let us know about your progress, please.

**Comment by jivanpal** [comment]
Unable to reproduce on a fresh install of PopOS 22.04 (Intel revision 23) using Docker Desktop 4.17.0 (99724) with Docker Engine v20.10.23. Closing.
