### ISSUE TITLE
Docker Desktop does never start in Manjaro Linux

### ISSUE THREAD

**Issue by SalahAdDin** [docker/desktop-linux#97]
- [x] I have tried the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: b774adb7-9266-467c-b866-89c65f984f91/20221126193022

### Expected behavior
We installed it in [Manjaro Linux](https://docs.docker.com/desktop/install/archlinux/) following the guide without any problem. It should never have any problem getting tokens and it should start properly. Also, at checking the common commands:

```
docker compose version
Docker Compose version v2.5.0
docker --version
Docker version 20.10.14, build a224086349
docker version
Client: Docker Engine - Community
Cloud integration: 1.0.24
Version:           20.10.14
API version:       1.41
```

### Actual behavior
Launching it we always have the following problem altogether with another bug we reported [here](https://github.com/docker/desktop-linux/issues/96#issuecomment-1328101100):
![Docker Desktop eternal starting.](https://user-images.githubusercontent.com/5034215/204106325-28ad0dc8-dff3-4536-92b5-cdc89538b6bd.png)

By checking the commands we get:
```
 docker compose version
exec: "com.docker.cli": executable file not found in $PATH
Current PATH : /home/luisalaguna/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/luisalaguna

docker --version
exec: "com.docker.cli": executable file not found in $PATH
Current PATH : /home/luisalaguna/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/luisalaguna

docker version
exec: "com.docker.cli": executable file not found in $PATH
Current PATH : /home/luisalaguna/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/luisalaguna
```

### Information

  - Linux distro: Manjaro Linux x86_64
  - Distro version: Manjaro Linux 21.3.7
  - Docker Desktop Version: 4.14.1

### Steps to reproduce the behavior

  1. Install Docker Desktop following the guide.
  2. Launch the application.
  3. Test commands in the terminal.

**Comment by aiordache** [comment]
Hi @SalahAdDin.  The logs you uploaded report an error related to the id mappings for filesharing:
```
 setting up ID maps for virtiofsd namespace: retrieving subordinate UID range: no range for <USER> found in /etc/subuid
```

You can check the docs at https://docs.docker.com/desktop/faqs/linuxfaqs/#how-do-i-enable-file-sharing on how to do it.

Concerning the `com.docker.cli`, first remove `/usr/local/bin/docker` and `/usr/local/bin/com.docker.cli` binaries. Then try to reinstall, the postinstall script from the arch package should set them up again.

**Comment by seth-seikosoft** [comment]
> * [x]  I have tried the latest version of Docker Desktop
> 
>     * [x]  I have tried disabling enabled experimental features
> 
>     * [x]  I have uploaded Diagnostics
> 
>     * Diagnostics ID: b774adb7-9266-467c-b866-89c65f984f91/20221126193022
> 
> 
> ### Expected behavior
> 
> We installed it in [Manjaro Linux](https://docs.docker.com/desktop/install/archlinux/) following the guide without any problem. It should never have any problem getting tokens and it should start properly. Also, at checking the common commands:
> 
> ```
> docker compose version
> Docker Compose version v2.5.0
> docker --version
> Docker version 20.10.14, build a224086349
> docker version
> Client: Docker Engine - Community
> Cloud integration: 1.0.24
> Version:           20.10.14
> API version:       1.41
> ```
> 
> ### Actual behavior
> 
> Launching it we always have the following problem altogether with another bug we reported [here](https://github.com/docker/desktop-linux/issues/96#issuecomment-1328101100): ![Docker Desktop eternal starting.](https://user-images.githubusercontent.com/5034215/204106325-28ad0dc8-dff3-4536-92b5-cdc89538b6bd.png)
> 
> By checking the commands we get:
> 
> ```
>  docker compose version
> exec: "com.docker.cli": executable file not found in $PATH
> Current PATH : /home/luisalaguna/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/luisalaguna
> 
> docker --version
> exec: "com.docker.cli": executable file not found in $PATH
> Current PATH : /home/luisalaguna/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/luisalaguna
> 
> docker version
> exec: "com.docker.cli": executable file not found in $PATH
> Current PATH : /home/luisalaguna/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/luisalaguna
> ```
> 
> ### Information
> 
>     * Linux distro: Manjaro Linux x86_64
> 
>     * Distro version: Manjaro Linux 21.3.7
> 
>     * Docker Desktop Version: 4.14.1
> 
> 
> ### Steps to reproduce the behavior
> 
>     1. Install Docker Desktop following the guide.
> 
>     2. Launch the application.
> 
>     3. Test commands in the terminal.

I was running into this same issue and I got it working!  

What I did to get it to work is after I installing docker desktop via [install](https://docs.docker.com/desktop/install/archlinux/) 

- run  `gpg --generate-key` 
- run `pass init <gpg key id>`
- run `sudo systemctl disable/stop docker docker.socket containerd`
- reboot
- run `systemctl --user start docker-desktop`

after that I signed into docker hub via the docker-desktop GUI.  

I ran through the tutorial after that to make sure everything was working. 

Hopefully that helps you out!

**Comment by SalahAdDin** [comment]
> I was running into this same issue and I got it working!
> 
> What I did to get it to work is after I installing docker desktop via [install](https://docs.docker.com/desktop/install/archlinux/)
> 
>     * run  `gpg --generate-key`
> 
>     * run `pass init <gpg key id>`
> 
>     * run `sudo systemctl disable/stop docker docker.socket containerd`
> 
>     * reboot
> 
>     * run `systemctl --user start docker-desktop`
> 
> 
> after that I signed into docker hub via the docker-desktop GUI.
> 
> I ran through the tutorial after that to make sure everything was working.
> 
> Hopefully that helps you out!

Where you using Manjaro?

**Comment by seth-seikosoft** [comment]
> > I was running into this same issue and I got it working!
> > What I did to get it to work is after I installing docker desktop via [install](https://docs.docker.com/desktop/install/archlinux/)
> > ```
> > * run  `gpg --generate-key`
> > 
> > * run `pass init <gpg key id>`
> > 
> > * run `sudo systemctl disable/stop docker docker.socket containerd`
> > 
> > * reboot
> > 
> > * run `systemctl --user start docker-desktop`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > after that I signed into docker hub via the docker-desktop GUI.
> > I ran through the tutorial after that to make sure everything was working.
> > Hopefully that helps you out!
> 
> Where you using Manjaro?

yes I was using Manjaro
